import { SupportedLanguage } from './types';

/**
 * Ghost and Equipment Localization Data
 * Maps IDs to translated names and descriptions
 */

export const ghostNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    spirit: 'Spirit',
    wraith: 'Wraith',
    phantom: 'Phantom',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Shade',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mimic',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  de: {
    spirit: 'Geist',
    wraith: 'Phantom',
    phantom: 'Trugbild',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Schatten',
    demon: 'Dämon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Nachahmer',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  nl: {
    spirit: 'Geest',
    wraith: 'Wraak',
    phantom: 'Fantoom',
    poltergeist: 'Poltergeest',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Schaduw',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Navolger',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  fr: {
    spirit: 'Esprit',
    wraith: 'Spectre',
    phantom: 'Fantôme',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Ombre',
    demon: 'Démon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mimic',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  es: {
    spirit: 'Espíritu',
    wraith: 'Espectro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Sombra',
    demon: 'Demonio',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Imitador',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  it: {
    spirit: 'Spirito',
    wraith: 'Spettro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Ombra',
    demon: 'Demone',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mitico',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  pt: {
    spirit: 'Espírito',
    wraith: 'Espectro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Sombra',
    demon: 'Demônio',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mímico',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  sv: {
    spirit: 'Anden',
    wraith: 'Vålnad',
    phantom: 'Fantom',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Skugga',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mimik',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
};

export const equipmentNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'EMF Reader': 'EMF Reader',
    'Spirit Box': 'Spirit Box',
    'Ghost Writing Book': 'Ghost Writing Book',
    Thermometer: 'Thermometer',
    'UV Flashlight': 'UV Flashlight',
    'Crucifix': 'Crucifix',
    'Salt': 'Salt',
    'Candle': 'Candle',
    'Smudge Sticks': 'Smudge Sticks',
    'Sanity Medication': 'Sanity Medication',
    'Sound Sensor': 'Sound Sensor',
    'Motion Sensor': 'Motion Sensor',
    'Video Camera': 'Video Camera',
    'Tripod': 'Tripod',
    'Headphones': 'Headphones',
    'Infrared Light Sensor': 'Infrared Light Sensor',
    'D.O.T.S. Projector': 'D.O.T.S. Projector',
    'Parabolic Microphone': 'Parabolic Microphone',
    'Laptop': 'Laptop',
  },
  de: {
    'EMF Reader': 'EMF-Messgerät',
    'Spirit Box': 'Geisterbox',
    'Ghost Writing Book': 'Geisterschreib-Buch',
    Thermometer: 'Thermometer',
    'UV Flashlight': 'UV-Taschenlampe',
    'Crucifix': 'Kruzifix',
    'Salt': 'Salz',
    'Candle': 'Kerze',
    'Smudge Sticks': 'Räucherstäbchen',
    'Sanity Medication': 'Sanität-Medizin',
    'Sound Sensor': 'Geräuschsensor',
    'Motion Sensor': 'Bewegungsmelder',
    'Video Camera': 'Videokamera',
    'Tripod': 'Stativ',
    'Headphones': 'Kopfhörer',
    'Infrared Light Sensor': 'Infrarot-Lichtsensor',
    'D.O.T.S. Projector': 'D.O.T.S. Projektor',
    'Parabolic Microphone': 'Parabolmikrofon',
    'Laptop': 'Laptop',
  },
  nl: {
    'EMF Reader': 'EMF-meter',
    'Spirit Box': 'Geestbox',
    'Ghost Writing Book': 'Geestschrijf-boek',
    Thermometer: 'Thermometer',
    'UV Flashlight': 'UV-zaklamp',
    'Crucifix': 'Crucifix',
    'Salt': 'Zout',
    'Candle': 'Kaars',
    'Smudge Sticks': 'Wierookstokken',
    'Sanity Medication': 'Geestelijkheidsmedicatie',
    'Sound Sensor': 'Geluidssensor',
    'Motion Sensor': 'Bewegingssensor',
    'Video Camera': 'Videocamera',
    'Tripod': 'Statief',
    'Headphones': 'Koptelefoon',
    'Infrared Light Sensor': 'Infrarood lichtsensor',
    'D.O.T.S. Projector': 'D.O.T.S. Projector',
    'Parabolic Microphone': 'Parabolische microfoon',
    'Laptop': 'Laptop',
  },
  fr: {
    'EMF Reader': 'Lecteur EMF',
    'Spirit Box': 'Boîte d\'esprits',
    'Ghost Writing Book': 'Livre d\'écriture fantôme',
    Thermometer: 'Thermomètre',
    'UV Flashlight': 'Lampe UV',
    'Crucifix': 'Crucifix',
    'Salt': 'Sel',
    'Candle': 'Bougie',
    'Smudge Sticks': 'Bâtons de sauge',
    'Sanity Medication': 'Médicament de santé mentale',
    'Sound Sensor': 'Capteur sonore',
    'Motion Sensor': 'Capteur de mouvement',
    'Video Camera': 'Caméra vidéo',
    'Tripod': 'Trépied',
    'Headphones': 'Casque audio',
    'Infrared Light Sensor': 'Capteur de lumière infrarouge',
    'D.O.T.S. Projector': 'Projecteur D.O.T.S.',
    'Parabolic Microphone': 'Microphone parabolique',
    'Laptop': 'Ordinateur portable',
  },
  es: {
    'EMF Reader': 'Lector EMF',
    'Spirit Box': 'Caja de espíritus',
    'Ghost Writing Book': 'Libro de escritura fantasmal',
    Thermometer: 'Termómetro',
    'UV Flashlight': 'Linterna UV',
    'Crucifix': 'Crucifijo',
    'Salt': 'Sal',
    'Candle': 'Vela',
    'Smudge Sticks': 'Varas de salvia',
    'Sanity Medication': 'Medicamento de cordura',
    'Sound Sensor': 'Sensor de sonido',
    'Motion Sensor': 'Sensor de movimiento',
    'Video Camera': 'Cámara de video',
    'Tripod': 'Trípode',
    'Headphones': 'Auriculares',
    'Infrared Light Sensor': 'Sensor de luz infrarroja',
    'D.O.T.S. Projector': 'Proyector D.O.T.S.',
    'Parabolic Microphone': 'Micrófono parabólico',
    'Laptop': 'Portátil',
  },
  it: {
    'EMF Reader': 'Lettore EMF',
    'Spirit Box': 'Scatola degli spiriti',
    'Ghost Writing Book': 'Libro di scrittura fantasma',
    Thermometer: 'Termometro',
    'UV Flashlight': 'Torcia UV',
    'Crucifix': 'Crocifisso',
    'Salt': 'Sale',
    'Candle': 'Candela',
    'Smudge Sticks': 'Bastoni di salvia',
    'Sanity Medication': 'Medicina della sanità mentale',
    'Sound Sensor': 'Sensore di suono',
    'Motion Sensor': 'Sensore di movimento',
    'Video Camera': 'Videocamera',
    'Tripod': 'Treppiede',
    'Headphones': 'Cuffie',
    'Infrared Light Sensor': 'Sensore di luce infrarossa',
    'D.O.T.S. Projector': 'Proiettore D.O.T.S.',
    'Parabolic Microphone': 'Microfono parabolico',
    'Laptop': 'Laptop',
  },
  pt: {
    'EMF Reader': 'Leitor EMF',
    'Spirit Box': 'Caixa de espíritos',
    'Ghost Writing Book': 'Livro de escrita fantasmagórica',
    Thermometer: 'Termômetro',
    'UV Flashlight': 'Lanterna UV',
    'Crucifix': 'Crucifixo',
    'Salt': 'Sal',
    'Candle': 'Vela',
    'Smudge Sticks': 'Varetas de sálvia',
    'Sanity Medication': 'Medicação de sanidade',
    'Sound Sensor': 'Sensor de som',
    'Motion Sensor': 'Sensor de movimento',
    'Video Camera': 'Câmera de vídeo',
    'Tripod': 'Tripé',
    'Headphones': 'Fones de ouvido',
    'Infrared Light Sensor': 'Sensor de luz infravermelha',
    'D.O.T.S. Projector': 'Projetor D.O.T.S.',
    'Parabolic Microphone': 'Microfone parabólico',
    'Laptop': 'Laptop',
  },
  sv: {
    'EMF Reader': 'EMF-läsare',
    'Spirit Box': 'Andelåda',
    'Ghost Writing Book': 'Spökskrivningsbok',
    Thermometer: 'Termometer',
    'UV Flashlight': 'UV-ficklampa',
    'Crucifix': 'Krusifiks',
    'Salt': 'Salt',
    'Candle': 'Ljus',
    'Smudge Sticks': 'Rökarstavar',
    'Sanity Medication': 'Sinnesgångs medicin',
    'Sound Sensor': 'Ljudsensor',
    'Motion Sensor': 'Rörelsesensor',
    'Video Camera': 'Videokamera',
    'Tripod': 'Stativ',
    'Headphones': 'Hörlurar',
    'Infrared Light Sensor': 'Infraröd ljussensor',
    'D.O.T.S. Projector': 'D.O.T.S. projektor',
    'Parabolic Microphone': 'Parabolisk mikrofon',
    'Laptop': 'Bärbar dator',
  },
};

/**
 * Helper function to get localized ghost name
 */
export const getGhostName = (ghostId: string, language: SupportedLanguage): string => {
  return ghostNames[language]?.[ghostId] || ghostNames.en[ghostId] || ghostId;
};

/**
 * Helper function to get localized equipment name
 */
export const getEquipmentName = (equipmentId: string, language: SupportedLanguage): string => {
  return equipmentNames[language]?.[equipmentId] || equipmentNames.en[equipmentId] || equipmentId;
};
