import { SupportedLanguage } from './types';

/**
 * Ghost and Equipment Localization Data
 * Maps IDs to translated names and descriptions
 */

export const ghostNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    spirit: 'Spirit',
    wraith: 'Wraith',
    phantom: 'Phantom',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Shade',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mimic',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  de: {
    spirit: 'Geist',
    wraith: 'Phantom',
    phantom: 'Trugbild',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Schatten',
    demon: 'Dämon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Nachahmer',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  nl: {
    spirit: 'Geest',
    wraith: 'Wraak',
    phantom: 'Fantoom',
    poltergeist: 'Poltergeest',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Schaduw',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Navolger',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  fr: {
    spirit: 'Esprit',
    wraith: 'Spectre',
    phantom: 'Fantôme',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Ombre',
    demon: 'Démon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mimic',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  es: {
    spirit: 'Espíritu',
    wraith: 'Espectro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Sombra',
    demon: 'Demonio',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Imitador',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  it: {
    spirit: 'Spirito',
    wraith: 'Spettro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Ombra',
    demon: 'Demone',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mitico',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  pt: {
    spirit: 'Espírito',
    wraith: 'Espectro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Sombra',
    demon: 'Demônio',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mímico',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
  sv: {
    spirit: 'Anden',
    wraith: 'Vålnad',
    phantom: 'Fantom',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Skugga',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    obake: 'Obake',
    mimic: 'Mimik',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
    goryo: 'Goryo',
    myling: 'Myling',
  },
};

export const equipmentNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'emf-reader': 'EMF Reader',
    'spirit-box': 'Spirit Box',
    'ghost-writing-book': 'Ghost Writing Book',
    'thermometer': 'Thermometer',
    'uv-light': 'UV Flashlight',
    'crucifix': 'Crucifix',
    'salt': 'Salt',
    'candle': 'Candle',
    'smudge-sticks': 'Smudge Sticks',
    'sanity-medication': 'Sanity Medication',
    'sound-sensor': 'Sound Sensor',
    'motion-sensor': 'Motion Sensor',
    'video-camera': 'Video Camera',
    'tripod': 'Tripod',
    'headphones': 'Headphones',
    'infrared-light-sensor': 'Infrared Light Sensor',
    'dots-projector': 'D.O.T.S. Projector',
    'parabolic-microphone': 'Parabolic Microphone',
    'laptop': 'Laptop',
  },
  de: {
    'emf-reader': 'EMF-Messgerät',
    'spirit-box': 'Geisterbox',
    'ghost-writing-book': 'Geisterschreib-Buch',
    'thermometer': 'Thermometer',
    'uv-light': 'UV-Taschenlampe',
    'crucifix': 'Kruzifix',
    'salt': 'Salz',
    'candle': 'Kerze',
    'smudge-sticks': 'Räucherstäbchen',
    'sanity-medication': 'Sanität-Medizin',
    'sound-sensor': 'Geräuschsensor',
    'motion-sensor': 'Bewegungsmelder',
    'video-camera': 'Videokamera',
    'tripod': 'Stativ',
    'headphones': 'Kopfhörer',
    'infrared-light-sensor': 'Infrarot-Lichtsensor',
    'dots-projector': 'D.O.T.S. Projektor',
    'parabolic-microphone': 'Parabolmikrofon',
    'laptop': 'Laptop',
  },
  nl: {
    'emf-reader': 'EMF-meter',
    'spirit-box': 'Geestbox',
    'ghost-writing-book': 'Geestschrijf-boek',
    'thermometer': 'Thermometer',
    'uv-light': 'UV-zaklamp',
    'crucifix': 'Crucifix',
    'salt': 'Zout',
    'candle': 'Kaars',
    'smudge-sticks': 'Wierookstokken',
    'sanity-medication': 'Geestelijkheidsmedicatie',
    'sound-sensor': 'Geluidssensor',
    'motion-sensor': 'Bewegingssensor',
    'video-camera': 'Videocamera',
    'tripod': 'Statief',
    'headphones': 'Koptelefoon',
    'infrared-light-sensor': 'Infrarood lichtsensor',
    'dots-projector': 'D.O.T.S. Projector',
    'parabolic-microphone': 'Parabolische microfoon',
    'laptop': 'Laptop',
  },
  fr: {
    'emf-reader': 'Lecteur EMF',
    'spirit-box': 'Boîte d\'esprits',
    'ghost-writing-book': 'Livre d\'écriture fantôme',
    'thermometer': 'Thermomètre',
    'uv-light': 'Lampe UV',
    'crucifix': 'Crucifix',
    'salt': 'Sel',
    'candle': 'Bougie',
    'smudge-sticks': 'Bâtons de sauge',
    'sanity-medication': 'Médicament de santé mentale',
    'sound-sensor': 'Capteur sonore',
    'motion-sensor': 'Capteur de mouvement',
    'video-camera': 'Caméra vidéo',
    'tripod': 'Trépied',
    'headphones': 'Casque audio',
    'infrared-light-sensor': 'Capteur de lumière infrarouge',
    'dots-projector': 'Projecteur D.O.T.S.',
    'parabolic-microphone': 'Microphone parabolique',
    'laptop': 'Ordinateur portable',
  },
  es: {
    'emf-reader': 'Lector EMF',
    'spirit-box': 'Caja de espíritus',
    'ghost-writing-book': 'Libro de escritura fantasmal',
    'thermometer': 'Termómetro',
    'uv-light': 'Linterna UV',
    'crucifix': 'Crucifijo',
    'salt': 'Sal',
    'candle': 'Vela',
    'smudge-sticks': 'Varas de salvia',
    'sanity-medication': 'Medicamento de cordura',
    'sound-sensor': 'Sensor de sonido',
    'motion-sensor': 'Sensor de movimiento',
    'video-camera': 'Cámara de video',
    'tripod': 'Trípode',
    'headphones': 'Auriculares',
    'infrared-light-sensor': 'Sensor de luz infrarroja',
    'dots-projector': 'Proyector D.O.T.S.',
    'parabolic-microphone': 'Micrófono parabólico',
    'laptop': 'Portátil',
  },
  it: {
    'emf-reader': 'Lettore EMF',
    'spirit-box': 'Scatola degli spiriti',
    'ghost-writing-book': 'Libro di scrittura fantasma',
    'thermometer': 'Termometro',
    'uv-light': 'Torcia UV',
    'crucifix': 'Crocifisso',
    'salt': 'Sale',
    'candle': 'Candela',
    'smudge-sticks': 'Bastoni di salvia',
    'sanity-medication': 'Medicina della sanità mentale',
    'sound-sensor': 'Sensore di suono',
    'motion-sensor': 'Sensore di movimento',
    'video-camera': 'Videocamera',
    'tripod': 'Treppiede',
    'headphones': 'Cuffie',
    'infrared-light-sensor': 'Sensore di luce infrarossa',
    'dots-projector': 'Proiettore D.O.T.S.',
    'parabolic-microphone': 'Microfono parabolico',
    'laptop': 'Laptop',
  },
  pt: {
    'emf-reader': 'Leitor EMF',
    'spirit-box': 'Caixa de espíritos',
    'ghost-writing-book': 'Livro de escrita fantasmagórica',
    'thermometer': 'Termômetro',
    'uv-light': 'Lanterna UV',
    'crucifix': 'Crucifixo',
    'salt': 'Sal',
    'candle': 'Vela',
    'smudge-sticks': 'Varetas de sálvia',
    'sanity-medication': 'Medicação de sanidade',
    'sound-sensor': 'Sensor de som',
    'motion-sensor': 'Sensor de movimento',
    'video-camera': 'Câmera de vídeo',
    'tripod': 'Tripé',
    'headphones': 'Fones de ouvido',
    'infrared-light-sensor': 'Sensor de luz infravermelha',
    'dots-projector': 'Projetor D.O.T.S.',
    'parabolic-microphone': 'Microfone parabólico',
    'laptop': 'Laptop',
  },
  sv: {
    'emf-reader': 'EMF-läsare',
    'spirit-box': 'Andelåda',
    'ghost-writing-book': 'Spökskrivningsbok',
    'thermometer': 'Termometer',
    'uv-light': 'UV-ficklampa',
    'crucifix': 'Krusifiks',
    'salt': 'Salt',
    'candle': 'Ljus',
    'smudge-sticks': 'Rökarstavar',
    'sanity-medication': 'Sinnesgångs medicin',
    'sound-sensor': 'Ljudsensor',
    'motion-sensor': 'Rörelsesensor',
    'video-camera': 'Videokamera',
    'tripod': 'Stativ',
    'headphones': 'Hörlurar',
    'infrared-light-sensor': 'Infraröd ljussensor',
    'dots-projector': 'D.O.T.S. projektor',
    'parabolic-microphone': 'Parabolisk mikrofon',
    'laptop': 'Bärbar dator',
  },
};

/**
 * Helper function to get localized ghost name
 */
export const getGhostName = (ghostId: string, language: SupportedLanguage): string => {
  return ghostNames[language]?.[ghostId] || ghostNames.en[ghostId] || ghostId;
};

/**
 * Helper function to get localized equipment name
 */
export const getEquipmentName = (equipmentId: string, language: SupportedLanguage): string => {
  return equipmentNames[language]?.[equipmentId] || equipmentNames.en[equipmentId] || equipmentId;
};

/**
 * Re-export ghost description helper from ghost-data module
 */
export { getGhostDescription } from './ghost-data';
