import { SupportedLanguage } from './types';

/**
 * Ghost and Equipment Localization Data
 * Maps IDs to translated names and descriptions
 */

export const ghostNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    spirit: 'Spirit',
    wraith: 'Wraith',
    phantom: 'Phantom',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Shade',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'The Mimic',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'The Twins',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  de: {
    spirit: 'Geist',
    wraith: 'Phantom',
    phantom: 'Trugbild',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Schatten',
    demon: 'Dämon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'Der Imitator',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'Die Zwillinge',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  nl: {
    spirit: 'Geest',
    wraith: 'Wraak',
    phantom: 'Fantoom',
    poltergeist: 'Poltergeest',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Schaduw',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'De Navolger',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'De Tweeling',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  fr: {
    spirit: 'Esprit',
    wraith: 'Spectre',
    phantom: 'Fantôme',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Ombre',
    demon: 'Démon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'Le Mimic',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'Les Jumeaux',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  es: {
    spirit: 'Espíritu',
    wraith: 'Espectro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Sombra',
    demon: 'Demonio',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'El Imitador',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'Los Gemelos',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  it: {
    spirit: 'Spirito',
    wraith: 'Spettro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Ombra',
    demon: 'Demone',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'Il Mitico',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'I Gemelli',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  pt: {
    spirit: 'Espírito',
    wraith: 'Espectro',
    phantom: 'Fantasma',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Sombra',
    demon: 'Demônio',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'O Mímicode',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'Os Gêmeos',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
  sv: {
    spirit: 'Anden',
    wraith: 'Vålnad',
    phantom: 'Fantom',
    poltergeist: 'Poltergeist',
    banshee: 'Banshee',
    jinn: 'Jinn',
    mare: 'Mare',
    revenant: 'Revenant',
    shade: 'Skugga',
    demon: 'Demon',
    yurei: 'Yurei',
    oni: 'Oni',
    yokai: 'Yokai',
    hantu: 'Hantu',
    goryo: 'Goryo',
    myling: 'Myling',
    onryo: 'Onryo',
    theMinic: 'Mimetikern',
    obake: 'Obake',
    moroi: 'Moroi',
    deogen: 'Deogen',
    thaye: 'Thaye',
    raiju: 'Raiju',
    theTwins: 'Tvillingarna',
    tsukomogami: 'Tsukomogami',
    kitsune: 'Kitsune',
  },
};

export const equipmentNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'emf-reader': 'EMF Reader',
    'spirit-box': 'Spirit Box',
    'ghost-writing-book': 'Ghost Writing Book',
    'thermometer': 'Thermometer',
    'uv-light': 'UV Flashlight',
    'video-camera': 'Video Camera',
    'dots-projector': 'D.O.T.S. Projector',
    'flashlight': 'Flashlight',
    'crucifix': 'Crucifix',
    'salt': 'Salt',
    'sanity-medication': 'Sanity Medication',
    'incense': 'Incense',
    'igniter': 'Igniter',
    'firelight': 'Firelight',
    'photo-camera': 'Photo Camera',
    'parabolic-microphone': 'Parabolic Microphone',
    'sound-recorder': 'Sound Recorder',
    'sound-sensor': 'Sound Sensor',
    'motion-sensor': 'Motion Sensor',
    'tripod': 'Tripod',
    'head-gear': 'Head Gear',
    'objective-board': 'Objective Board',
    'site-map': 'Site Map',
    'sanity-monitor': 'Sanity Monitor',
    'site-activity-monitor': 'Site Activity Monitor',
    'computer': 'Computer',
    'sound-monitor': 'Sound Monitor',
    'clipboards': 'Clipboards',
    'setup-timer': 'Setup Timer',
    'ouija-board': 'Ouija Board',
    'tarot-cards': 'Tarot Cards',
    'music-box': 'Music Box',
    'haunted-mirror': 'Haunted Mirror',
    'voodoo-doll': 'Voodoo Doll',
    'summoning-circle': 'Summoning Circle',
    'monkey-paw': 'Monkey Paw',
  },
  de: {
    'emf-reader': 'EMF-Messgerät',
    'spirit-box': 'Geisterbox',
    'ghost-writing-book': 'Geisterschreib-Buch',
    'thermometer': 'Thermometer',
    'uv-light': 'UV-Taschenlampe',
    'video-camera': 'Videokamera',
    'dots-projector': 'D.O.T.S. Projektor',
    'flashlight': 'Taschenlampe',
    'crucifix': 'Kruzifix',
    'salt': 'Salz',
    'sanity-medication': 'Sanität-Medizin',
    'incense': 'Räucherstäbchen',
    'igniter': 'Feuerzeug',
    'firelight': 'Lagerfeuer',
    'photo-camera': 'Fotokamera',
    'parabolic-microphone': 'Parabolmikrofon',
    'sound-recorder': 'Tonbandgerät',
    'sound-sensor': 'Geräuschsensor',
    'motion-sensor': 'Bewegungsmelder',
    'tripod': 'Stativ',
    'head-gear': 'Kopfkamera',
    'objective-board': 'Aufgabentafel',
    'site-map': 'Übersichtskarte',
    'sanity-monitor': 'Geistzustandsmonitor',
    'site-activity-monitor': 'Aktivitätsmonitor',
    'computer': 'Computer',
    'sound-monitor': 'Geräuschmonitor',
    'clipboards': 'Klemmbrett',
    'setup-timer': 'Aufbau-Timer',
    'ouija-board': 'Ouija-Brett',
    'tarot-cards': 'Tarotkarten',
    'music-box': 'Spieldose',
    'haunted-mirror': 'Verfluchter Spiegel',
    'voodoo-doll': 'Voodoo-Puppe',
    'summoning-circle': 'Beschwörungskreis',
    'monkey-paw': 'Affenpfote',
  },
  nl: {
    'emf-reader': 'EMF-meter',
    'spirit-box': 'Geestbox',
    'ghost-writing-book': 'Geestschrijf-boek',
    'thermometer': 'Thermometer',
    'uv-light': 'UV-zaklamp',
    'video-camera': 'Videocamera',
    'dots-projector': 'D.O.T.S. Projector',
    'flashlight': 'Zaklamp',
    'crucifix': 'Crucifix',
    'salt': 'Zout',
    'sanity-medication': 'Geestelijkheidsmedicatie',
    'incense': 'Wierookstokken',
    'igniter': 'Aansteker',
    'firelight': 'Kampvuur',
    'photo-camera': 'Fotocamera',
    'parabolic-microphone': 'Parabolische microfoon',
    'sound-recorder': 'Geluidsrecorder',
    'sound-sensor': 'Geluidssensor',
    'motion-sensor': 'Bewegingssensor',
    'tripod': 'Statief',
    'head-gear': 'Kopkamera',
    'objective-board': 'Doelenbord',
    'site-map': 'Locatiekaart',
    'sanity-monitor': 'Geestelijkheidmonitor',
    'site-activity-monitor': 'Activiteitenmonitor',
    'computer': 'Computer',
    'sound-monitor': 'Geluidsmonitor',
    'clipboards': 'Klemborden',
    'setup-timer': 'Installatietimer',
    'ouija-board': 'Ouija-bord',
    'tarot-cards': 'Tarotkaarten',
    'music-box': 'Speeldoos',
    'haunted-mirror': 'Spookspiegel',
    'voodoo-doll': 'Voodoopop',
    'summoning-circle': 'Bezweringscirkel',
    'monkey-paw': 'Apehand',
  },
  fr: {
    'emf-reader': 'Lecteur EMF',
    'spirit-box': 'Boîte d\'esprits',
    'ghost-writing-book': 'Livre d\'écriture fantôme',
    'thermometer': 'Thermomètre',
    'uv-light': 'Lampe UV',
    'video-camera': 'Caméra vidéo',
    'dots-projector': 'Projecteur D.O.T.S.',
    'flashlight': 'Lampe de poche',
    'crucifix': 'Crucifix',
    'salt': 'Sel',
    'sanity-medication': 'Médicament de santé mentale',
    'incense': 'Bâtons de sauge',
    'igniter': 'Briquet',
    'firelight': 'Lumière de campagne',
    'photo-camera': 'Appareil photo',
    'parabolic-microphone': 'Microphone parabolique',
    'sound-recorder': 'Enregistreur sonore',
    'sound-sensor': 'Capteur sonore',
    'motion-sensor': 'Capteur de mouvement',
    'tripod': 'Trépied',
    'head-gear': 'Caméra montée sur la tête',
    'objective-board': 'Tableau des objectifs',
    'site-map': 'Carte du site',
    'sanity-monitor': 'Moniteur de santé mentale',
    'site-activity-monitor': 'Moniteur d\'activité',
    'computer': 'Ordinateur',
    'sound-monitor': 'Moniteur sonore',
    'clipboards': 'Presse-papiers',
    'setup-timer': 'Minuterie de configuration',
    'ouija-board': 'Planche de Ouija',
    'tarot-cards': 'Cartes de tarot',
    'music-box': 'Boîte à musique',
    'haunted-mirror': 'Miroir hanté',
    'voodoo-doll': 'Poupée vaudou',
    'summoning-circle': 'Cercle d\'invocation',
    'monkey-paw': 'Patte de singe',
  },
  es: {
    'emf-reader': 'Lector EMF',
    'spirit-box': 'Caja de espíritus',
    'ghost-writing-book': 'Libro de escritura fantasmal',
    'thermometer': 'Termómetro',
    'uv-light': 'Linterna UV',
    'video-camera': 'Cámara de video',
    'dots-projector': 'Proyector D.O.T.S.',
    'flashlight': 'Linterna',
    'crucifix': 'Crucifijo',
    'salt': 'Sal',
    'sanity-medication': 'Medicamento de cordura',
    'incense': 'Varas de salvia',
    'igniter': 'Encendedor',
    'firelight': 'Luz de fuego',
    'photo-camera': 'Cámara fotográfica',
    'parabolic-microphone': 'Micrófono parabólico',
    'sound-recorder': 'Grabadora de sonido',
    'sound-sensor': 'Sensor de sonido',
    'motion-sensor': 'Sensor de movimiento',
    'tripod': 'Trípode',
    'head-gear': 'Cámara de cabeza',
    'objective-board': 'Tablero de objetivos',
    'site-map': 'Mapa del sitio',
    'sanity-monitor': 'Monitor de cordura',
    'site-activity-monitor': 'Monitor de actividad',
    'computer': 'Computadora',
    'sound-monitor': 'Monitor de sonido',
    'clipboards': 'Pizarras',
    'setup-timer': 'Temporizador de configuración',
    'ouija-board': 'Tablero de Ouija',
    'tarot-cards': 'Cartas de tarot',
    'music-box': 'Caja de música',
    'haunted-mirror': 'Espejo embrujado',
    'voodoo-doll': 'Muñeca vudú',
    'summoning-circle': 'Círculo de invocación',
    'monkey-paw': 'Pata de mono',
  },
  it: {
    'emf-reader': 'Lettore EMF',
    'spirit-box': 'Scatola degli spiriti',
    'ghost-writing-book': 'Libro di scrittura fantasma',
    'thermometer': 'Termometro',
    'uv-light': 'Torcia UV',
    'video-camera': 'Videocamera',
    'dots-projector': 'Proiettore D.O.T.S.',
    'flashlight': 'Torcia',
    'crucifix': 'Crocifisso',
    'salt': 'Sale',
    'sanity-medication': 'Medicina della sanità mentale',
    'incense': 'Bastoni di salvia',
    'igniter': 'Accendino',
    'firelight': 'Fuoco da campo',
    'photo-camera': 'Fotocamera',
    'parabolic-microphone': 'Microfono parabolico',
    'sound-recorder': 'Registratore audio',
    'sound-sensor': 'Sensore di suono',
    'motion-sensor': 'Sensore di movimento',
    'tripod': 'Treppiede',
    'head-gear': 'Videocamera montata sulla testa',
    'objective-board': 'Lavagna degli obiettivi',
    'site-map': 'Mappa del sito',
    'sanity-monitor': 'Monitor sanità mentale',
    'site-activity-monitor': 'Monitor attività',
    'computer': 'Computer',
    'sound-monitor': 'Monitor audio',
    'clipboards': 'Appunti',
    'setup-timer': 'Timer di configurazione',
    'ouija-board': 'Tavola Ouija',
    'tarot-cards': 'Carte dei tarocchi',
    'music-box': 'Carillon',
    'haunted-mirror': 'Specchio infestato',
    'voodoo-doll': 'Bambola vudù',
    'summoning-circle': 'Cerchio di invocazione',
    'monkey-paw': 'Zampa di scimmia',
  },
  pt: {
    'emf-reader': 'Leitor EMF',
    'spirit-box': 'Caixa de espíritos',
    'ghost-writing-book': 'Livro de escrita fantasmagórica',
    'thermometer': 'Termômetro',
    'uv-light': 'Lanterna UV',
    'video-camera': 'Câmera de vídeo',
    'dots-projector': 'Projetor D.O.T.S.',
    'flashlight': 'Lanterna',
    'crucifix': 'Crucifixo',
    'salt': 'Sal',
    'sanity-medication': 'Medicação de sanidade',
    'incense': 'Varetas de sálvia',
    'igniter': 'Acendedor',
    'firelight': 'Luz de fogo',
    'photo-camera': 'Câmera fotográfica',
    'parabolic-microphone': 'Microfone parabólico',
    'sound-recorder': 'Gravador de áudio',
    'sound-sensor': 'Sensor de som',
    'motion-sensor': 'Sensor de movimento',
    'tripod': 'Tripé',
    'head-gear': 'Câmera montada na cabeça',
    'objective-board': 'Quadro de objetivos',
    'site-map': 'Mapa do site',
    'sanity-monitor': 'Monitor de sanidade',
    'site-activity-monitor': 'Monitor de atividade',
    'computer': 'Computador',
    'sound-monitor': 'Monitor de som',
    'clipboards': 'Pranchetas',
    'setup-timer': 'Temporizador de configuração',
    'ouija-board': 'Tabuleiro Ouija',
    'tarot-cards': 'Cartas de tarô',
    'music-box': 'Caixa de música',
    'haunted-mirror': 'Espelho assombrado',
    'voodoo-doll': 'Boneco vodu',
    'summoning-circle': 'Círculo de invocação',
    'monkey-paw': 'Pata de macaco',
  },
  sv: {
    'emf-reader': 'EMF-läsare',
    'spirit-box': 'Andelåda',
    'ghost-writing-book': 'Spökskrivningsbok',
    'thermometer': 'Termometer',
    'uv-light': 'UV-ficklampa',
    'video-camera': 'Videokamera',
    'dots-projector': 'D.O.T.S. projektor',
    'flashlight': 'Ficklampa',
    'crucifix': 'Krusifiks',
    'salt': 'Salt',
    'sanity-medication': 'Sinnesgångs medicin',
    'incense': 'Rökarstavar',
    'igniter': 'Tändstickor',
    'firelight': 'Eldskål',
    'photo-camera': 'Fotokamera',
    'parabolic-microphone': 'Parabolisk mikrofon',
    'sound-recorder': 'Ljudinspelare',
    'sound-sensor': 'Ljudsensor',
    'motion-sensor': 'Rörelsesensor',
    'tripod': 'Stativ',
    'head-gear': 'Huvudkamera',
    'objective-board': 'Målstavla',
    'site-map': 'Platskarta',
    'sanity-monitor': 'Sinnesgångsövervakning',
    'site-activity-monitor': 'Aktivitetsövervakning',
    'computer': 'Dator',
    'sound-monitor': 'Ljudövervakning',
    'clipboards': 'Klemmapp',
    'setup-timer': 'Setuptimmer',
    'ouija-board': 'Ouija-bräde',
    'tarot-cards': 'Tarotkort',
    'music-box': 'Speldosa',
    'haunted-mirror': 'Spökspeglre',
    'voodoo-doll': 'Voodoodocka',
    'summoning-circle': 'Besväringscirkel',
    'monkey-paw': 'Aphand',
  },
};

/**
 * Helper function to get localized ghost name
 */
export const getGhostName = (ghostId: string, language: SupportedLanguage): string => {
  return ghostNames[language]?.[ghostId] || ghostNames.en[ghostId] || ghostId;
};

/**
 * Helper function to get localized equipment name
 */
export const getEquipmentName = (equipmentId: string, language: SupportedLanguage): string => {
  return equipmentNames[language]?.[equipmentId] || equipmentNames.en[equipmentId] || equipmentId;
};

/**
 * Re-export ghost description helper from ghost-data module
 */
export { getGhostDescription } from './ghost-data';
