/**
 * Equipment Data Localization
 * Descriptions, usage, and recommendations for all equipment
 */

import { SupportedLanguage } from './types';

// Equipment descriptions
export const equipmentDescriptions: Record<string, Record<SupportedLanguage, string>> = {
  'emf-reader': {
    en: 'Detects electromagnetic fields to identify ghost presence and activity',
    de: 'Erkennt elektromagnetische Felder um Geistpräsenz zu identifizieren',
    nl: 'Detecteert elektromagnetische velden om geestpresence te identificeren',
    fr: 'Détecte les champs électromagnétiques pour identifier la présence de fantômes',
    es: 'Detecta campos electromagnéticos para identificar presencia de fantasmas',
    it: 'Rileva campi elettromagnetici per identificare la presenza di fantasmi',
    pt: 'Detecta campos eletromagnéticos para identificar presença de fantasmas',
    sv: 'Detekterar elektromagnetiska fält för att identifiera spökesnärvaro',
  },
  'spirit-box': {
    en: 'Allows communication with ghosts through white noise and radio frequencies',
    de: 'Ermöglicht Kommunikation mit Geistern durch weißes Rauschen',
    nl: 'Maakt communicatie met geesten mogelijk door witruisgeluiden',
    fr: 'Permet la communication avec les fantômes par bruit blanc',
    es: 'Permite comunicarse con fantasmas a través de ruido blanco',
    it: 'Permette la comunicazione con i fantasmi tramite rumore bianco',
    pt: 'Permite comunicação com fantasmas através de ruído branco',
    sv: 'Tillåter kommunikation med spöken genom vita ljud',
  },
  'ghost-writing-book': {
    en: 'Records ghost writing to collect evidence of paranormal activity',
    de: 'Zeichnet Geisterschrift auf um paranormale Aktivität zu dokumentieren',
    nl: 'Registreert geestschrift om paranormale activiteit vast te leggen',
    fr: 'Enregistre les écritures de fantômes pour documenter l\'activité paranormale',
    es: 'Registra escritura de fantasmas para documentar actividad paranormal',
    it: 'Registra la scrittura di fantasmi per documentare l\'attività paranormale',
    pt: 'Registra escritura de fantasmas para documentar atividade paranormal',
    sv: 'Registrerar spökeskrivning för att dokumentera paranormal aktivitet',
  },
  'thermometer': {
    en: 'Measures temperature changes to detect supernatural cold spots',
    de: 'Misst Temperaturänderungen um übernatürliche Kaltstellen zu erkennen',
    nl: 'Meet temperatuurveranderingen om bovennatuurlijke koude plekken op te sporen',
    fr: 'Mesure les changements de température pour détecter les points froids surnaturels',
    es: 'Mide cambios de temperatura para detectar puntos fríos sobrenaturales',
    it: 'Misura i cambiamenti di temperatura per rilevare punti freddi sovrannaturali',
    pt: 'Mede mudanças de temperatura para detectar pontos frios sobrenaturais',
    sv: 'Mäter temperaturförändringar för att detektera övernaturliga kalla punkter',
  },
  'uv-light': {
    en: 'Reveals invisible fingerprints left by ghosts under ultraviolet light',
    de: 'Offenbart unsichtbare Fingerabdrücke von Geistern unter UV-Licht',
    nl: 'Onthult onzichtbare vingerafdrukken van geesten onder UV-licht',
    fr: 'Révèle les empreintes digitales invisibles des fantômes sous la lumière UV',
    es: 'Revela las huellas dactilares invisibles de fantasmas bajo luz UV',
    it: 'Rivela le impronte digitali invisibili dei fantasmi sotto la luce UV',
    pt: 'Revela as impressões digitais invisíveis de fantasmas sob luz UV',
    sv: 'Avslöjar osynliga fingeravtryck från spöken under UV-ljus',
  },
  'crucifix': {
    en: 'Prevents ghosts from hunting within a certain radius when placed strategically',
    de: 'Verhindert Geistjagden innerhalb eines bestimmten Radius',
    nl: 'Voorkomt geestjachten binnen een bepaalde radius',
    fr: 'Empêche la chasse des fantômes dans un certain rayon',
    es: 'Evita que los fantasmas cacen dentro de un cierto radio',
    it: 'Impedisce ai fantasmi di cacciare entro un certo raggio',
    pt: 'Evita que os fantasmas cacem dentro de um certo raio',
    sv: 'Förhindrar spökjakt inom en viss radie',
  },
  'salt': {
    en: 'Salt piles that ghosts interact with to leave footprints. Used to track ghost movement patterns',
    de: 'Salzhaufen mit denen Geister interagieren und Fußabdrücke hinterlassen',
    nl: 'Zouthopen waarmee geesten interacteren om voetstappen achter te laten',
    fr: 'Des tas de sel avec lesquels les fantômes interagissent pour laisser des empreintes',
    es: 'Montones de sal con los que los fantasmas interactúan para dejar huellas',
    it: 'Mucchi di sale con cui i fantasmi interagiscono per lasciare impronte',
    pt: 'Pilhas de sal com as quais os fantasmas interagem para deixar pegadas',
    sv: 'Salthögar som spöken interagerar med för att lämna fotspår',
  },
  'dots-projector': {
    en: 'Projects laser dots that reveal ghost silhouettes when the ghost passes through',
    de: 'Projiziert Laserpunkte die Geistsilhouetten offenbaren',
    nl: 'Projecteert laserpunten die geestsilhouetten onthullen',
    fr: 'Projette des points laser qui révèlent les silhouettes de fantômes',
    es: 'Proyecta puntos láser que revelan las siluetas de fantasmas',
    it: 'Proietta punti laser che rivelano le silhouette dei fantasmi',
    pt: 'Projeta pontos de laser que revelam silhuetas de fantasmas',
    sv: 'Projicerar laserpunkter som avslöjar spöksilhuetter',
  },
  'video-camera': {
    en: 'Records video evidence including ghost manifestations and D.O.T.S. interactions',
    de: 'Zeichnet Videobeweise auf einschließlich Geistmanifestationen',
    nl: 'Neemt videobewijs op inclusief geestmanifestaties',
    fr: 'Enregistre les preuves vidéo y compris les manifestations de fantômes',
    es: 'Registra pruebas de video incluyendo manifestaciones de fantasmas',
    it: 'Registra prove video incluse manifestazioni di fantasmi',
    pt: 'Registra provas de vídeo incluindo manifestações de fantasmas',
    sv: 'Spelar in videobevisen inklusive spökemanifestationer',
  },
  'parabolic-microphone': {
    en: 'Captures paranormal sounds and ghost vocalizations from a distance',
    de: 'Erfasst paranormale Geräusche und Geistlokalisierungen aus der Ferne',
    nl: 'Legt paranormale geluiden en geestgeluideen vast van afstand',
    fr: 'Capture les sons paranormaux et les vocalisations de fantômes de loin',
    es: 'Captura sonidos paranormales y vocalizaciones de fantasmas desde la distancia',
    it: 'Cattura suoni paranormali e vocalizzazioni di fantasmi da lontano',
    pt: 'Captura sons paranormais e vocalizações de fantasmas de longe',
    sv: 'Fångar paranormala ljud och spökvokalisationer från långt bort',
  },
  'sanity-medication': {
    en: 'Restores sanity to players, essential for surviving dangerous encounters',
    de: 'Stellt Geist wieder her, wesentlich zum Überleben gefährlicher Begegnungen',
    nl: 'Herstelt zielkracht, essentieel om gevaarlijke ontmoetingen te overleven',
    fr: 'Restaure la sanité, essentiel pour survivre aux rencontres dangereuses',
    es: 'Restaura la cordura, esencial para sobrevivir encuentros peligrosos',
    it: 'Ripristina la sanità, essenziale per sopravvivere agli incontri pericolosi',
    pt: 'Restaura sanidade, essencial para sobreviver encontros perigosos',
    sv: 'Återställer förstånd, väsentligt för att överleva farliga möten',
  },
  'flashlight': {
    en: 'Standard light source for illumination in dark areas. Can malfunction during ghost activity.',
    de: 'Standard-Lichtquelle zur Beleuchtung. Kann bei Geistaktivität ausfallen.',
    nl: 'Standaard lichtbron voor verlichting in donkere gebieden.',
    fr: 'Source de lumière standard pour l\'illumination. Peut mal fonctionner pendant l\'activité des fantômes.',
    es: 'Fuente de luz estándar para iluminación. Puede no funcionar durante la actividad de fantasmas.',
    it: 'Fonte di luce standard per l\'illuminazione. Può malfunzionare durante l\'attività dei fantasmi.',
    pt: 'Fonte de luz padrão para iluminação. Pode não funcionar durante atividade de fantasmas.',
    sv: 'Standardljuskälla för belysning. Kan inte fungera under spökaktivitet.',
  },
  'incense': {
    en: 'Incense sticks that prevent ghost hunts temporarily. Also blinds ghosts during hunts.',
    de: 'Räucherstäbchen die vorübergehend Geistjagden verhindern.',
    nl: 'Wierookstokken die geestjachten tijdelijk voorkomen.',
    fr: 'Bâtons d\'encens qui empêchent temporairement les chasses de fantômes.',
    es: 'Varas de incienso que evitan temporalmente la caza de fantasmas.',
    it: 'Bastoni d\'incenso che impediscono temporaneamente la caccia ai fantasmi.',
    pt: 'Varetas de incenso que impedem temporariamente a caça de fantasmas.',
    sv: 'Rökkarstavar som förhindrar spökjakt tillfälligt.',
  },
  'igniter': {
    en: 'Lighter for starting fires and lighting equipment like incense and firelight.',
    de: 'Feuerzeug zum Anzünden von Feuer und Ausrüstung.',
    nl: 'Aansteker voor het aansteken van vuur en apparatuur.',
    fr: 'Briquet pour allumer des feux et l\'équipement.',
    es: 'Encendedor para encender fuegos y equipos.',
    it: 'Accendino per accendere fuochi e attrezzature.',
    pt: 'Isqueiro para acender fogos e equipamentos.',
    sv: 'Tändstickor för att tända eldar och utrustning.',
  },
  'firelight': {
    en: 'Portable campfire that provides warmth and reduces sanity drain when lit.',
    de: 'Tragbares Lagerfeuer das Wärme bietet und Geistzustandsverlust reduziert.',
    nl: 'Draagbaar kampvuur dat warmte biedt en zielkrachtsverlies vermindert.',
    fr: 'Feu de camp portable qui offre chaleur et réduit la perte de sanité.',
    es: 'Fuego de campamento portátil que proporciona calor y reduce la pérdida de cordura.',
    it: 'Fuoco da campo portatile che offre calore e riduce la perdita di sanità.',
    pt: 'Fogo de acampamento portátil que oferece calor e reduz perda de sanidade.',
    sv: 'Bärbart lägereld som ger värme och minskar förståndförlust.',
  },
  'photo-camera': {
    en: 'Camera for taking photos of ghosts and evidence. Earn money for photos.',
    de: 'Kamera zum Fotografieren von Geistern und Beweisen.',
    nl: 'Camera voor het fotograferen van geesten en bewijzen.',
    fr: 'Appareil photo pour prendre des photos de fantômes et de preuves.',
    es: 'Cámara para tomar fotos de fantasmas y evidencia.',
    it: 'Fotocamera per scattare foto di fantasmi e prove.',
    pt: 'Câmera para tirar fotos de fantasmas e evidências.',
    sv: 'Kamera för att ta bilder av spöken och bevis.',
  },
  'sound-recorder': {
    en: 'Records paranormal sounds from the environment. Captures EVP evidence.',
    de: 'Zeichnet paranormale Geräusche auf.',
    nl: 'Neemt paranormale geluiden op.',
    fr: 'Enregistre les sons paranormaux de l\'environnement.',
    es: 'Registra sonidos paranormales del entorno.',
    it: 'Registra i suoni paranormali dall\'ambiente.',
    pt: 'Grava sons paranormais do ambiente.',
    sv: 'Spelar in paranormala ljud från miljön.',
  },
  'sound-sensor': {
    en: 'Detects near-inaudible sounds and relays data to truck monitor.',
    de: 'Erkennt kaum hörbare Geräusche und überträgt Daten.',
    nl: 'Detecteert nauwelijks hoorbare geluiden.',
    fr: 'Détecte les sons presque inaudibles.',
    es: 'Detecta sonidos apenas audibles.',
    it: 'Rileva suoni quasi inaudibili.',
    pt: 'Detecta sons quase inaudíveis.',
    sv: 'Detekterar nästan ohörbara ljud.',
  },
  'motion-sensor': {
    en: 'Detects movement from both ghosts and players. Most expensive equipment.',
    de: 'Erkennt Bewegungen von Geistern und Spielern.',
    nl: 'Detecteert beweging van geesten en spelers.',
    fr: 'Détecte les mouvements des fantômes et des joueurs.',
    es: 'Detecta movimiento de fantasmas y jugadores.',
    it: 'Rileva il movimento di fantasmi e giocatori.',
    pt: 'Detecta movimento de fantasmas e jogadores.',
    sv: 'Detekterar rörelse från spöken och spelare.',
  },
  'tripod': {
    en: 'Mount for video cameras. Reduces ghost priority for throwing during hunts.',
    de: 'Halterung für Videokameras.',
    nl: 'Montage voor videocamera\'s.',
    fr: 'Monture pour caméras vidéo.',
    es: 'Montura para cámaras de video.',
    it: 'Staffa per fotocamere video.',
    pt: 'Suporte para câmeras de vídeo.',
    sv: 'Montering för videokameror.',
  },
  'head-gear': {
    en: 'Head-mounted camera providing first-person video feed to truck.',
    de: 'Kopfkamera die First-Person-Videostream liefert.',
    nl: 'Kopfkamera met eerstepersoonsvideo naar vrachtwagen.',
    fr: 'Caméra montée sur la tête fournissant un flux vidéo à la première personne.',
    es: 'Cámara montada en la cabeza que proporciona video en primera persona.',
    it: 'Fotocamera montata sulla testa che fornisce video in prima persona.',
    pt: 'Câmera montada na cabeça fornecendo vídeo em primeira pessoa.',
    sv: 'Huvudmonterad kamera som ger förstapersson videofeed.',
  },
  'objective-board': {
    en: 'Displays all mandatory and optional objectives for current contract.',
    de: 'Zeigt alle obligatorischen und optionalen Ziele an.',
    nl: 'Toont alle verplichte en optionele doelstellingen.',
    fr: 'Affiche tous les objectifs obligatoires et optionnels.',
    es: 'Muestra todos los objetivos obligatorios y opcionales.',
    it: 'Visualizza tutti gli obiettivi obbligatori e facoltativi.',
    pt: 'Exibe todos os objetivos obrigatórios e opcionais.',
    sv: 'Visar alla obligatoriska och valfria mål.',
  },
  'site-map': {
    en: 'Provides detailed map of location with room layouts and connections.',
    de: 'Bietet detaillierte Karte der Ortschaft mit Raumlayouts.',
    nl: 'Biedt gedetailleerde kaart van locatie met kamer layouts.',
    fr: 'Fournit une carte détaillée du site avec les dispositions des pièces.',
    es: 'Proporciona mapa detallado del sitio con disposiciones de salas.',
    it: 'Fornisce mappa dettagliata del sito con layout delle stanze.',
    pt: 'Fornece mapa detalhado do local com layouts de sala.',
    sv: 'Tillhandahåller detaljerad karta över webbplatsen med rumslayouter.',
  },
  'sanity-monitor': {
    en: 'Real-time display of all players sanity levels.',
    de: 'Echtzeitanzeige aller Spieler-Geistzustände.',
    nl: 'Realtime weergave van alle speelszielkracht.',
    fr: 'Affichage en temps réel de tous les niveaux de sanité des joueurs.',
    es: 'Pantalla en tiempo real de todos los niveles de cordura de los jugadores.',
    it: 'Visualizzazione in tempo reale di tutti i livelli di sanità dei giocatori.',
    pt: 'Exibição em tempo real de todos os níveis de sanidade dos jogadores.',
    sv: 'Realtidsvisning av alla spelarnas förståndnivåer.',
  },
  'site-activity-monitor': {
    en: 'Displays ghost activity and hunt alerts in real-time.',
    de: 'Zeigt Geistaktivität und Jagdalerts an.',
    nl: 'Toont geestactiviteit en jachtwaarschuwingen.',
    fr: 'Affiche l\'activité des fantômes et les alertes de chasse.',
    es: 'Muestra la actividad de fantasmas y alertas de caza.',
    it: 'Visualizza l\'attività dei fantasmi e gli avvisi di caccia.',
    pt: 'Exibe atividade de fantasmas e alertas de caça.',
    sv: 'Visar spökaktivitet och jaktvarningar.',
  },
  'computer': {
    en: 'Main computer for viewing all video camera feeds simultaneously.',
    de: 'Hauptcomputer zum Anzeigen aller Videokamerafeeds.',
    nl: 'Hoofdcomputer voor het bekijken van alle videocamerafeeds.',
    fr: 'Ordinateur principal pour afficher tous les flux des caméras vidéo.',
    es: 'Computadora principal para ver todos los feeds de cámara de video.',
    it: 'Computer principale per visualizzare tutti i feed delle telecamere.',
    pt: 'Computador principal para visualizar todos os feeds da câmera de vídeo.',
    sv: 'Huvuddator för att visa alla videokameraflöden.',
  },
  'sound-monitor': {
    en: 'Connects to sound sensors placed on site for audio monitoring.',
    de: 'Verbindet sich mit Geräuschsensoren vor Ort.',
    nl: 'Verbindt met geluidssensoren op locatie.',
    fr: 'Se connecte aux capteurs sonores placés sur le site.',
    es: 'Se conecta a sensores de sonido colocados en el sitio.',
    it: 'Si connette ai sensori di suono posizionati sul sito.',
    pt: 'Conecta-se a sensores de som colocados no local.',
    sv: 'Ansluter till ljudsensorer placerade på webbplatsen.',
  },
  'clipboards': {
    en: 'Shows current daily and weekly tasks and challenges.',
    de: 'Zeigt aktuelle tägliche und wöchentliche Aufgaben.',
    nl: 'Toont huidige dagelijkse en wekelijkse taken.',
    fr: 'Affiche les tâches et défis quotidiens et hebdomadaires actuels.',
    es: 'Muestra las tareas y desafíos diarios y semanales actuales.',
    it: 'Visualizza le attività e i compiti quotidiani e settimanali attuali.',
    pt: 'Exibe tarefas e desafios diários e semanais atuais.',
    sv: 'Visar aktuella dagliga och veckovisa uppgifter.',
  },
  'setup-timer': {
    en: 'Displays remaining time in setup phase before ghost can hunt.',
    de: 'Zeigt verbleibende Zeit in der Aufbauphase an.',
    nl: 'Toont resterende tijd in opstellingsfase.',
    fr: 'Affiche le temps restant dans la phase de configuration.',
    es: 'Muestra el tiempo restante en la fase de configuración.',
    it: 'Visualizza il tempo rimanente nella fase di configurazione.',
    pt: 'Exibe o tempo restante na fase de configuração.',
    sv: 'Visar återstående tid i installationsfasen.',
  },
  'ouija-board': {
    en: 'Ancient board for communicating with spirits. Interaction drains significant sanity.',
    de: 'Altes Brett zum Kommunizieren mit Geistern. Kostet viel Geistzustand.',
    nl: 'Oud bord voor communicatie met geesten.',
    fr: 'Ancien plateau pour communiquer avec les esprits.',
    es: 'Tablero antiguo para comunicarse con espíritus.',
    it: 'Antico tavolo per comunicare con gli spiriti.',
    pt: 'Tabuleiro antigo para comunicação com espíritos.',
    sv: 'Forntida bräde för att kommunicera med andar.',
  },
  'tarot-cards': {
    en: 'Draw cards for mysterious effects. Highly unpredictable but can be beneficial.',
    de: 'Ziehe Karten für mysteriöse Effekte.',
    nl: 'Trek kaarten voor mysterieuze effecten.',
    fr: 'Tirez des cartes pour des effets mystérieux.',
    es: 'Dibuja cartas para efectos misteriosos.',
    it: 'Estrai carte per effetti misteriosi.',
    pt: 'Puxe cartas para efeitos misteriosos.',
    sv: 'Dra kort för mystiska effekter.',
  },
  'music-box': {
    en: 'Plays eerie music. Nearby players lose sanity continuously while playing.',
    de: 'Spielt unheimliche Musik. Spieler verlieren Geistzustand.',
    nl: 'Speelt griezelige muziek. Spelers verliezen zielkracht.',
    fr: 'Joue une musique étrange. Les joueurs perdent la sanité à proximité.',
    es: 'Toca música espeluznante. Los jugadores pierden cordura.',
    it: 'Suona una musica inquietante. I giocatori perdono sanità.',
    pt: 'Toca música assustadora. Jogadores perdem sanidade.',
    sv: 'Spelar spöksignalen musik. Spelare förlorar förstånd.',
  },
  'haunted-mirror': {
    en: 'Mirror with dark presence. Interacting drains significant sanity.',
    de: 'Spiegel mit dunkler Präsenz. Kostet viel Geistzustand.',
    nl: 'Spiegel met donkere aanwezigheid.',
    fr: 'Miroir avec une présence sombre.',
    es: 'Espejo con presencia oscura.',
    it: 'Specchio con una presenza oscura.',
    pt: 'Espelho com presença escura.',
    sv: 'Spegel med mörk närvaro.',
  },
  'voodoo-doll': {
    en: 'Ancient doll with pins. Using pins causes pain and sanity loss.',
    de: 'Uralte Puppe mit Nadeln. Verursacht Schmerz und Geistzustandsverlust.',
    nl: 'Oude pop met spelden.',
    fr: 'Poupée ancienne avec des épingles.',
    es: 'Muñeca antigua con alfileres.',
    it: 'Bambola antica con spilli.',
    pt: 'Boneca antiga com alfinetes.',
    sv: 'Urpsrunglig docka med spel.',
  },
  'summoning-circle': {
    en: 'Circle for summoning supernatural entities. Extremely dangerous.',
    de: 'Kreis zum Beschwören übernatürlicher Wesenheiten.',
    nl: 'Cirkel voor het oproepen van bovennatuurlijke wezens.',
    fr: 'Cercle pour invoquer des entités surnaturelles.',
    es: 'Círculo para invocar entidades sobrenaturales.',
    it: 'Cerchio per invocare entità sovrannaturali.',
    pt: 'Círculo para invocar entidades sobrenaturais.',
    sv: 'Cirkel för att framkalla övernaturliga väsen.',
  },
  'monkey-paw': {
    en: 'Legendary cursed object. Grants wishes with terrible consequences.',
    de: 'Legendärer verfluchter Gegenstand. Erfüllt Wünsche mit Konsequenzen.',
    nl: 'Legendarisch vervloekt object.',
    fr: 'Objet légendaire maudit.',
    es: 'Objeto legendario maldito.',
    it: 'Oggetto leggendario maledetto.',
    pt: 'Objeto lendário amaldiçoado.',
    sv: 'Legendarisk förbannad föremål.',
  },
};

// Equipment usage tips
export const equipmentUsage: Record<string, Record<SupportedLanguage, string>> = {
  'emf-reader': {
    en: 'Place near suspected ghost activity areas. EMF Level 5 readings are strong evidence.',
    de: 'Platzieren Sie in der Nähe vermuteter Geistaktivitätsbereiche.',
    nl: 'Plaats in de buurt van vermoede geestactiviteitsbereiken.',
    fr: 'Placez près des zones d\'activité de fantômes suspectes.',
    es: 'Coloca cerca de áreas de actividad de fantasmas sospechosa.',
    it: 'Posiziona vicino alle aree di attività di fantasmi sospette.',
    pt: 'Coloque perto de áreas de atividade de fantasmas suspeita.',
    sv: 'Placera nära misstänkta spökaktivitetsområden.',
  },
  'spirit-box': {
    en: 'Ask questions to communicate with the ghost. More active with certain ghost types.',
    de: 'Stellen Sie Fragen um mit dem Geist zu kommunizieren.',
    nl: 'Stel vragen om met de geest te communiceren.',
    fr: 'Posez des questions pour communiquer avec le fantôme.',
    es: 'Haz preguntas para comunicarte con el fantasma.',
    it: 'Fai domande per comunicare con il fantasma.',
    pt: 'Faça perguntas para se comunicar com o fantasma.',
    sv: 'Ställ frågor för att kommunicera med spöket.',
  },
  'ghost-writing-book': {
    en: 'Place in ghost room and wait for it to write. Check frequently for messages.',
    de: 'Platzieren Sie im Geisterzimmer und warten Sie auf Schrift.',
    nl: 'Plaats in het geesterkamer en wacht op schrift.',
    fr: 'Placez dans la chambre du fantôme et attendez qu\'il écrive.',
    es: 'Coloca en la habitación del fantasma y espera que escriba.',
    it: 'Posiziona nella stanza del fantasma e aspetta che scriva.',
    pt: 'Coloque no quarto do fantasma e espere que escreva.',
    sv: 'Placera i spökrummet och vänta på att det skriver.',
  },
  'thermometer': {
    en: 'Hold in hand and watch for temperature drops below 10°C.',
    de: 'Halten Sie in der Hand und beobachten Sie Temperaturabfälle.',
    nl: 'Houd in hand en kijk naar temperatuurdalingen.',
    fr: 'Tenez en main et observez les chutes de température.',
    es: 'Sostén en la mano y observa caídas de temperatura.',
    it: 'Tieni in mano e osserva i cali di temperatura.',
    pt: 'Segure na mão e observe quedas de temperatura.',
    sv: 'Håll i hand och iaktta temperaturfall.',
  },
  'uv-light': {
    en: 'Shine on surfaces where ghost has touched. Look for glowing fingerprints.',
    de: 'Richten Sie auf Oberflächen wo der Geist berührt hat.',
    nl: 'Richt op oppervlakken waar geest is aangeraakt.',
    fr: 'Brillez sur les surfaces touchées par le fantôme.',
    es: 'Brilla sobre superficies tocadas por el fantasma.',
    it: 'Illumina le superfici toccate dal fantasma.',
    pt: 'Brilhe nas superfícies tocadas pelo fantasma.',
    sv: 'Lysa på ytor som spöket har rört.',
  },
  'video-camera': {
    en: 'Place on tripod or mount on wall. Monitor screen to watch feed for Ghost Orbs.',
    de: 'Platzieren Sie auf Stativ oder Wandhalterung.',
    nl: 'Plaats op statief of wandbevestiging.',
    fr: 'Placez sur trépied ou montage mural.',
    es: 'Coloca sobre trípode o montaje mural.',
    it: 'Posiziona su treppiede o montaggio a parete.',
    pt: 'Coloque sobre tripé ou montagem na parede.',
    sv: 'Placera på stativ eller väggmontering.',
  },
  'dots-projector': {
    en: 'Place in rooms where ghost activity is suspected. Watch for silhouettes.',
    de: 'Platzieren Sie in Räumen mit vermuteter Geistaktivität.',
    nl: 'Plaats in kamers met vermoede geestactiviteit.',
    fr: 'Placez dans les pièces où l\'activité des fantômes est suspecte.',
    es: 'Coloca en habitaciones donde se sospecha actividad de fantasmas.',
    it: 'Posiziona in stanze dove è sospetta l\'attività dei fantasmi.',
    pt: 'Coloque em cômodos onde a atividade de fantasmas é suspeita.',
    sv: 'Placera i rum där spökaktivitet misstänks.',
  },
  'flashlight': {
    en: 'Hold and activate for illumination. Will flicker and fail during ghost events.',
    de: 'Halten und aktivieren zur Beleuchtung.',
    nl: 'Houd vast en activeer voor verlichting.',
    fr: 'Tenez et activez pour l\'illumination.',
    es: 'Sostén y activa para la iluminación.',
    it: 'Tieni e attiva per l\'illuminazione.',
    pt: 'Segure e ative para iluminação.',
    sv: 'Håll och aktivera för belysning.',
  },
  'crucifix': {
    en: 'Place on ground near ghost spawn. Creates 3m protection radius.',
    de: 'Platzieren Sie auf dem Boden in der Nähe des Geistspawns.',
    nl: 'Plaats op de grond in de buurt van geestspawn.',
    fr: 'Placez sur le sol près de l\'apparition du fantôme.',
    es: 'Coloca en el suelo cerca del aparición del fantasma.',
    it: 'Posiziona sul terreno vicino all\'apparizione del fantasma.',
    pt: 'Coloque no chão perto do aparecimento do fantasma.',
    sv: 'Placera på marken nära spökapparitionen.',
  },
  'salt': {
    en: 'Place salt piles in high-traffic areas. Ghost will walk through and leave footprints visible with UV light.',
    de: 'Platzieren Sie Salzhaufen in stark frequentierten Bereichen. Geister hinterlassen Fußabdrücke.',
    nl: 'Plaats zouthopen in drukke gebieden. Geesten laten voetstappen achter zichtbaar met UV-licht.',
    fr: 'Placez des tas de sel dans les zones à fort trafic. Les fantômes laissent des empreintes visibles avec UV.',
    es: 'Coloca montones de sal en áreas de alto tráfico. Los fantasmas dejan huellas visibles con luz UV.',
    it: 'Posiziona mucchi di sale nelle aree ad alto traffico. I fantasmi lasciano impronte visibili con UV.',
    pt: 'Coloque pilhas de sal em áreas de alto tráfego. Fantasmas deixam pegadas visíveis com UV.',
    sv: 'Placera salthögar i högtrafik områden. Spöken lämnar fotspår synliga med UV-ljus.',
  },
  'incense': {
    en: 'Light with igniter. Prevents hunts for 60-120 seconds depending on difficulty.',
    de: 'Zünden Sie mit Feuerzeug an.',
    nl: 'Steek aan met aansteker.',
    fr: 'Allumez avec un briquet.',
    es: 'Enciende con encendedor.',
    it: 'Accendi con accendino.',
    pt: 'Acenda com isqueiro.',
    sv: 'Tända med tändstickor.',
  },
  'igniter': {
    en: 'Use to light incense and firelight. Also works on campfires.',
    de: 'Verwenden Sie zum Anzünden von Räucherstäbchen und Lagerfeuer.',
    nl: 'Gebruik om wierookstokken en vuurlicht aan te steken.',
    fr: 'Utilisez pour allumer l\'encens et le feu de camp.',
    es: 'Usa para encender incienso y luz de fuego.',
    it: 'Usa per accendere incenso e fuoco da campo.',
    pt: 'Use para acender incenso e luz de fogo.',
    sv: 'Använd för att tända rökkarstavar och eldskål.',
  },
  'firelight': {
    en: 'Light with igniter. Reduces sanity drain by 20-40% based on tier.',
    de: 'Zünden Sie mit Feuerzeug an.',
    nl: 'Steek aan met aansteker.',
    fr: 'Allumez avec un briquet.',
    es: 'Enciende con encendedor.',
    it: 'Accendi con accendino.',
    pt: 'Acenda com isqueiro.',
    sv: 'Tända med tändstickor.',
  },
  'photo-camera': {
    en: 'Take photos of ghosts, bodies, bones, and interactions. Earn $5-15 per photo.',
    de: 'Fotografieren Sie Geister, Leichen und Interaktionen.',
    nl: 'Fotografeer geesten, lijken en interacties.',
    fr: 'Photographiez les fantômes, les cadavres et les interactions.',
    es: 'Fotografía fantasmas, cadáveres e interacciones.',
    it: 'Fotografa fantasmi, cadaveri e interazioni.',
    pt: 'Fotografe fantasmas, cadáveres e interações.',
    sv: 'Fotografera spöken, lik och interaktioner.',
  },
  'parabolic-microphone': {
    en: 'Hold and listen for paranormal sounds. Ghosts vocalize every 80-127 seconds.',
    de: 'Halten Sie fest und hören Sie auf paranormale Geräusche.',
    nl: 'Houd vast en luister naar paranormale geluiden.',
    fr: 'Tenez et écoutez les sons paranormaux.',
    es: 'Sostén y escucha sonidos paranormales.',
    it: 'Tieni e ascolta i suoni paranormali.',
    pt: 'Segure e ouça sons paranormais.',
    sv: 'Håll och lyssna efter paranormala ljud.',
  },
  'sound-recorder': {
    en: 'Hold in ghost room. Records environmental sounds and ghost vocalizations.',
    de: 'Halten Sie im Geisterzimmer fest.',
    nl: 'Houd in geesterkamer vast.',
    fr: 'Tenez dans la chambre du fantôme.',
    es: 'Sostén en la habitación del fantasma.',
    it: 'Tieni nella stanza del fantasma.',
    pt: 'Segure no quarto do fantasma.',
    sv: 'Håll i spökrummet.',
  },
  'sound-sensor': {
    en: 'Place in ghost room. Detects ghost activity and displays on truck monitor.',
    de: 'Platzieren Sie im Geisterzimmer.',
    nl: 'Plaats in geesterkamer.',
    fr: 'Placez dans la chambre du fantôme.',
    es: 'Coloca en la habitación del fantasma.',
    it: 'Posiziona nella stanza del fantasma.',
    pt: 'Coloque no quarto do fantasma.',
    sv: 'Placera i spökrummet.',
  },
  'motion-sensor': {
    en: 'Place in hallways and pathways. Flashes when motion is detected.',
    de: 'Platzieren Sie in Fluren und Wegen.',
    nl: 'Plaats in gangen en paden.',
    fr: 'Placez dans les couloirs et les chemins.',
    es: 'Coloca en pasillos y caminos.',
    it: 'Posiziona in corridoi e percorsi.',
    pt: 'Coloque em corredores e caminhos.',
    sv: 'Placera i korridorer och vägar.',
  },
  'tripod': {
    en: 'Mount camera on tripod instead of holding for hands-free recording.',
    de: 'Montieren Sie die Kamera auf Stativ.',
    nl: 'Monteer camera op statief.',
    fr: 'Montez la caméra sur trépied.',
    es: 'Monta la cámara en trípode.',
    it: 'Monta la telecamera su treppiede.',
    pt: 'Monte a câmera no tripé.',
    sv: 'Montera kamera på stativ.',
  },
  'head-gear': {
    en: 'Equip on head. Provides first-person video feed to truck monitor.',
    de: 'Auf den Kopf ausrüsten.',
    nl: 'Uitrust op het hoofd.',
    fr: 'Équipez sur la tête.',
    es: 'Equipa en la cabeza.',
    it: 'Equipaggia sulla testa.',
    pt: 'Equipar na cabeça.',
    sv: 'Utrusta på huvudet.',
  },
  'objective-board': {
    en: 'Located on truck wall. Shows mandatory and optional objectives.',
    de: 'Befindet sich auf der Lastwagenwand.',
    nl: 'Bevindt zich op de vrachtwagenmuur.',
    fr: 'Situé sur le mur du camion.',
    es: 'Ubicado en la pared del camión.',
    it: 'Situato sul muro del camion.',
    pt: 'Localizado na parede do caminhão.',
    sv: 'Belägen på lastbilsväggen.',
  },
  'site-map': {
    en: 'Located on truck monitor. Shows all rooms and layout information.',
    de: 'Befindet sich auf dem Lastwagen-Monitor.',
    nl: 'Bevindt zich op de vrachtwagensmonitor.',
    fr: 'Situé sur l\'écran du camion.',
    es: 'Ubicado en la pantalla del camión.',
    it: 'Situato sullo schermo del camion.',
    pt: 'Localizado na tela do caminhão.',
    sv: 'Belägen på lastbilens skärm.',
  },
  'sanity-monitor': {
    en: 'Located on truck monitor. Shows individual and average team sanity.',
    de: 'Befindet sich auf dem Lastwagen-Monitor.',
    nl: 'Bevindt zich op de vrachtwagensmonitor.',
    fr: 'Situé sur l\'écran du camion.',
    es: 'Ubicado en la pantalla del camión.',
    it: 'Situato sullo schermo del camion.',
    pt: 'Localizado na tela do caminhão.',
    sv: 'Belägen på lastbilens skärm.',
  },
  'site-activity-monitor': {
    en: 'Located on truck monitor. Shows when ghost events and hunts occur.',
    de: 'Befindet sich auf dem Lastwagen-Monitor.',
    nl: 'Bevindt zich op de vrachtwagensmonitor.',
    fr: 'Situé sur l\'écran du camion.',
    es: 'Ubicado en la pantalla del camión.',
    it: 'Situato sullo schermo del camion.',
    pt: 'Localizado na tela do caminhão.',
    sv: 'Belägen på lastbilens skärm.',
  },
  'computer': {
    en: 'Located in truck. View multiple video camera feeds simultaneously.',
    de: 'Befindet sich im Lastwagen.',
    nl: 'Bevindt zich in de vrachtwagen.',
    fr: 'Situé dans le camion.',
    es: 'Ubicado en el camión.',
    it: 'Situato nel camion.',
    pt: 'Localizado no caminhão.',
    sv: 'Belägen i lastbilen.',
  },
  'sound-monitor': {
    en: 'Located in truck. Displays data from sound sensors placed on site.',
    de: 'Befindet sich im Lastwagen.',
    nl: 'Bevindt zich in de vrachtwagen.',
    fr: 'Situé dans le camion.',
    es: 'Ubicado en el camión.',
    it: 'Situato nel camion.',
    pt: 'Localizado no caminhão.',
    sv: 'Belägen i lastbilen.',
  },
  'clipboards': {
    en: 'Located on truck wall. Displays active daily and weekly challenges.',
    de: 'Befindet sich an der Lastwagenwand.',
    nl: 'Bevindt zich aan de vrachtwagenmuur.',
    fr: 'Situé sur le mur du camion.',
    es: 'Ubicado en la pared del camión.',
    it: 'Situato sul muro del camion.',
    pt: 'Localizado na parede do caminhão.',
    sv: 'Belägen på lastbilsväggen.',
  },
  'setup-timer': {
    en: 'Located on truck. Starts when exit door opens. Shows setup phase duration.',
    de: 'Befindet sich im Lastwagen.',
    nl: 'Bevindt zich in de vrachtwagen.',
    fr: 'Situé dans le camion.',
    es: 'Ubicado en el camión.',
    it: 'Situato nel camion.',
    pt: 'Localizado no caminhão.',
    sv: 'Belägen i lastbilen.',
  },
  'ouija-board': {
    en: 'Found on location. Ask questions about ghost. Drain per answer: Yes/No=40%, Maybe=20%.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
  'tarot-cards': {
    en: 'Found on location. Draw card for mysterious effect. The Sun=+100%, Moon=-100%.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
  'music-box': {
    en: 'Found on location. When activated, plays music. Nearby players drain sanity.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
  'haunted-mirror': {
    en: 'Found on location. Interact to use. Costs 20% sanity or 7.5% per second.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
  'voodoo-doll': {
    en: 'Found on location. Insert pins to drain sanity. Normal=5%, Heart=10%.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
  'summoning-circle': {
    en: 'Found on location. Light candles to summon ghost. Each drains 16% sanity nearby.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
  'monkey-paw': {
    en: 'Found on location. Make wish for mysterious consequence. Be sane=50%, Weather=-25%.',
    de: 'Wird am Standort gefunden.',
    nl: 'Gevonden op locatie.',
    fr: 'Trouvé sur le site.',
    es: 'Encontrado en la ubicación.',
    it: 'Trovato sulla posizione.',
    pt: 'Encontrado na localização.',
    sv: 'Hittad på plats.',
  },
};

/**
 * Helper functions
 */
export const getEquipmentDescription = (equipmentId: string, language: SupportedLanguage): string => {
  return equipmentDescriptions[equipmentId]?.[language] ?? equipmentDescriptions[equipmentId]?.en ?? '';
};

export const getEquipmentUsage = (equipmentId: string, language: SupportedLanguage): string => {
  return equipmentUsage[equipmentId]?.[language] ?? equipmentUsage[equipmentId]?.en ?? '';
};
