/**
 * Ghost Abilities, Strengths, Weaknesses, and Tips Localization
 * Complete translations across 8 languages
 */

import { SupportedLanguage } from './types';

// Ghost Abilities
export const ghostAbilities: Record<string, Record<SupportedLanguage, { name: string; description: string }>> = {
  spirit_poltergeist: {
    en: { name: 'Poltergeist-like Activity', description: 'Throws objects around the area' },
    de: { name: 'Poltergeist-ähnliche Aktivität', description: 'Wirft Objekte in der Umgebung herum' },
    nl: { name: 'Poltergeist-achtige activiteit', description: 'Gooit objecten rond in het gebied' },
    fr: { name: 'Activité de type Poltergeist', description: 'Lance des objets autour de la zone' },
    es: { name: 'Actividad tipo Poltergeist', description: 'Lanza objetos alrededor del área' },
    it: { name: 'Attività simile a Poltergeist', description: 'Lancia oggetti intorno all\'area' },
    pt: { name: 'Atividade tipo Poltergeist', description: 'Lança objetos ao redor da área' },
    sv: { name: 'Poltergeist-liknande aktivitet', description: 'Kastar föremål runt området' },
  },
  wraith_levitation: {
    en: { name: 'Levitation', description: 'Can levitate and pass through objects' },
    de: { name: 'Levitation', description: 'Kann schweben und durch Objekte gehen' },
    nl: { name: 'Levitatie', description: 'Kan zweven en door objecten gaan' },
    fr: { name: 'Lévitation', description: 'Peut léviter et passer à travers les objets' },
    es: { name: 'Levitación', description: 'Puede levitar y pasar a través de objetos' },
    it: { name: 'Levitazione', description: 'Può levitare e passare attraverso gli oggetti' },
    pt: { name: 'Levitação', description: 'Pode levitar e passar através de objetos' },
    sv: { name: 'Levitation', description: 'Kan levitra och passera genom objekt' },
  },
  wraith_teleportation: {
    en: { name: 'Teleportation', description: 'Can teleport to players' },
    de: { name: 'Teleportation', description: 'Kann sich zu Spielern teleportieren' },
    nl: { name: 'Teleportatie', description: 'Kan zich naar spelers teleporteren' },
    fr: { name: 'Téléportation', description: 'Peut se téléporter vers les joueurs' },
    es: { name: 'Teletransportación', description: 'Puede teletransportarse a los jugadores' },
    it: { name: 'Teletrasporto', description: 'Può teletrasportarsi ai giocatori' },
    pt: { name: 'Teletransporte', description: 'Pode se teletransportar para jogadores' },
    sv: { name: 'Teleportation', description: 'Kan teleportera sig till spelare' },
  },
  phantom_possession: {
    en: { name: 'Possession', description: 'Can temporarily control players' },
    de: { name: 'Besitzergreifung', description: 'Kann Spieler vorübergehend kontrollieren' },
    nl: { name: 'Bezitneming', description: 'Kan spelers tijdelijk controleren' },
    fr: { name: 'Possession', description: 'Peut contrôler temporairement les joueurs' },
    es: { name: 'Posesión', description: 'Puede controlar temporalmente a los jugadores' },
    it: { name: 'Possessione', description: 'Può controllare temporaneamente i giocatori' },
    pt: { name: 'Possessão', description: 'Pode controlar temporariamente os jogadores' },
    sv: { name: 'Possession', description: 'Kan tillfälligt kontrollera spelare' },
  },
  phantom_sanity_drain: {
    en: { name: 'Sanity Drain from Sight', description: 'Looking at the phantom drains sanity' },
    de: { name: 'Geistabzug beim Anblick', description: 'Das Anschauen des Phantoms verursacht Geistabzug' },
    nl: { name: 'Zielkracht afvoer', description: 'Naar het fantoom kijken voert zielkracht af' },
    fr: { name: 'Drain de santé mentale à la vue', description: 'Regarder le fantôme draine la santé mentale' },
    es: { name: 'Drenaje de cordura por vista', description: 'Mirar al fantasma drena la cordura' },
    it: { name: 'Drenaggio della sanità dalla vista', description: 'Guardare il fantasma drena la sanità' },
    pt: { name: 'Drenagem de sanidade pela visão', description: 'Olhar para o fantasma drena a sanidade' },
    sv: { name: 'Sinnesfördärvning från anblick', description: 'Att titta på fantomen dränerar förståndet' },
  },
  poltergeist_throwing: {
    en: { name: 'Object Throwing', description: 'Throws multiple objects at high velocities' },
    de: { name: 'Objektwurf', description: 'Wirft mehrere Objekte mit hoher Geschwindigkeit' },
    nl: { name: 'Objectwerpen', description: 'Werpt meerdere objecten met hoge snelheid' },
    fr: { name: 'Lancement d\'objets', description: 'Lance plusieurs objets à haute vélocité' },
    es: { name: 'Lanzamiento de objetos', description: 'Lanza múltiples objetos a alta velocidad' },
    it: { name: 'Lancio di oggetti', description: 'Lancia più oggetti ad alta velocità' },
    pt: { name: 'Lançamento de objetos', description: 'Lança múltiplos objetos em alta velocidade' },
    sv: { name: 'Objektkastning', description: 'Kastar flera objekt i höga hastigheter' },
  },
  banshee_scream: {
    en: { name: 'Scream', description: 'Emits a distinctive wail affecting the target' },
    de: { name: 'Schrei', description: 'Stößt einen unverwechselbaren Schrei aus' },
    nl: { name: 'Schreeuw', description: 'Stoot een onderscheidende kreet uit' },
    fr: { name: 'Cri', description: 'Émet un gémissement distinctif' },
    es: { name: 'Grito', description: 'Emite un grito distintivo' },
    it: { name: 'Urlo', description: 'Emette un grido distintivo' },
    pt: { name: 'Grito', description: 'Emite um grito distintivo' },
    sv: { name: 'Skrik', description: 'Utstöter ett karakteristiskt tjut' },
  },
  jinn_ability: {
    en: { name: 'Ability', description: 'Drains sanity from nearby players when breaker is on' },
    de: { name: 'Fähigkeit', description: 'Entzieht Geist von nahegelegenen Spielern wenn Brecher an' },
    nl: { name: 'Vermogen', description: 'Voert zielkracht af van dichtbijzijnde spelers' },
    fr: { name: 'Capacité', description: 'Draine la sanité des joueurs proches si le disjoncteur est allumé' },
    es: { name: 'Capacidad', description: 'Drena cordura de jugadores cercanos cuando el disyuntor está encendido' },
    it: { name: 'Capacità', description: 'Drena la sanità dai giocatori vicini quando l\'interruttore è acceso' },
    pt: { name: 'Capacidade', description: 'Drena sanidade de jogadores próximos quando o disjuntor está ligado' },
    sv: { name: 'Förmåga', description: 'Dränerar förstånd från närliggande spelare när strömbrytaren är på' },
  },
  mare_lights: {
    en: { name: 'Light Control', description: 'Turns off lights immediately after they are turned on' },
    de: { name: 'Lichtkontrolle', description: 'Schaltet Lichter sofort nach dem Einschalten aus' },
    nl: { name: 'Lichtcontrole', description: 'Schakelt lampen direct uit nadat ze zijn ingeschakeld' },
    fr: { name: 'Contrôle des lumières', description: 'Éteint les lumières immédiatement après leur allumage' },
    es: { name: 'Control de luces', description: 'Apaga las luces inmediatamente después de que se encienden' },
    it: { name: 'Controllo delle luci', description: 'Spegne le luci immediatamente dopo che si accendono' },
    pt: { name: 'Controle de luzes', description: 'Apaga as luzes imediatamente após serem acesas' },
    sv: { name: 'Ljuskontroll', description: 'Slår av lampor omedelbar efter att de tänds' },
  },
  revenant_speed: {
    en: { name: 'Slow/Fast Movement', description: 'Slow when not detecting players, very fast when detected' },
    de: { name: 'Langsame/Schnelle Bewegung', description: 'Langsam ohne Spieler, sehr schnell mit Spieler' },
    nl: { name: 'Langzame/Snelle beweging', description: 'Langzaam zonder spelers, erg snel met spelers' },
    fr: { name: 'Mouvement lent/rapide', description: 'Lent sans joueurs, très rapide avec joueurs' },
    es: { name: 'Movimiento lento/rápido', description: 'Lento sin jugadores, muy rápido con jugadores' },
    it: { name: 'Movimento lento/veloce', description: 'Lento senza giocatori, molto veloce con giocatori' },
    pt: { name: 'Movimento lento/rápido', description: 'Lento sem jogadores, muito rápido com jogadores' },
    sv: { name: 'Långsam/snabb rörelse', description: 'Långsam utan spelare, mycket snabb med spelare' },
  },
  shade_shyness: {
    en: { name: 'Shyness', description: 'Avoids activity when players are nearby' },
    de: { name: 'Schüchternheit', description: 'Vermeidet Aktivität wenn Spieler in der Nähe sind' },
    nl: { name: 'Verlegen', description: 'Vermijdt activiteit wanneer spelers in de buurt zijn' },
    fr: { name: 'Timidité', description: 'Évite l\'activité quand les joueurs sont proches' },
    es: { name: 'Timidez', description: 'Evita la actividad cuando hay jugadores cercanos' },
    it: { name: 'Timidezza', description: 'Evita l\'attività quando i giocatori sono vicini' },
    pt: { name: 'Timidez', description: 'Evita atividade quando jogadores estão próximos' },
    sv: { name: 'Blyghet', description: 'Undviker aktivitet när spelare är närvarande' },
  },
  demon_aggression: {
    en: { name: 'Aggression', description: 'Can initiate hunts at any sanity level' },
    de: { name: 'Aggression', description: 'Kann Jagden bei jedem Geistniveau beginnen' },
    nl: { name: 'Agressie', description: 'Kan jachten op elk zielkrachtniveau starten' },
    fr: { name: 'Agression', description: 'Peut initier des chasses à n\'importe quel niveau de sanité' },
    es: { name: 'Agresión', description: 'Puede iniciar caza a cualquier nivel de cordura' },
    it: { name: 'Aggressione', description: 'Può iniziare cacce a qualsiasi livello di sanità' },
    pt: { name: 'Agressão', description: 'Pode iniciar caçadas em qualquer nível de sanidade' },
    sv: { name: 'Aggression', description: 'Kan initiera jakter på vilken förståndsnivå som helst' },
  },
  yurei_door_slamming: {
    en: { name: 'Door Slamming & Sanity Drain', description: 'Slams doors and drains sanity from nearby players' },
    de: { name: 'Türenschlag & Geistabzug', description: 'Schlägt Türen zu und entzieht nahegelegenen Spielern Geist' },
    nl: { name: 'Deur slaan & zielkracht afvoer', description: 'Slaat deuren dicht en voert zielkracht af' },
    fr: { name: 'Claquement de porte & Drain de sanité', description: 'Claque les portes et draine la sanité' },
    es: { name: 'Portazo & Drenaje de cordura', description: 'Cierra puertas de golpe y drena cordura' },
    it: { name: 'Sbattere la porta & Drenaggio della sanità', description: 'Sbatte le porte e drena la sanità' },
    pt: { name: 'Batida de porta & Drenagem de sanidade', description: 'Bate portas e drena sanidade' },
    sv: { name: 'Dörrslagning & Sinnesfördärvning', description: 'Slamrar dörrar och dränerar förstånd' },
  },
  oni_aggression: {
    en: { name: 'Aggression Near Players', description: 'More active when near other players' },
    de: { name: 'Aggression in Spielernähe', description: 'Aktiver wenn Spieler in der Nähe sind' },
    nl: { name: 'Agressie dichtbij spelers', description: 'Actiever wanneer spelers in de buurt zijn' },
    fr: { name: 'Agression près des joueurs', description: 'Plus actif quand les joueurs sont proches' },
    es: { name: 'Agresión cerca de jugadores', description: 'Más activo cuando hay jugadores cerca' },
    it: { name: 'Aggressione vicino ai giocatori', description: 'Più attivo quando i giocatori sono vicini' },
    pt: { name: 'Agressão perto de jogadores', description: 'Mais ativo quando há jogadores próximos' },
    sv: { name: 'Aggression nära spelare', description: 'Mer aktivt när spelare är närvarande' },
  },
  yokai_voice: {
    en: { name: 'Voice Sensitivity', description: 'Can hunt at higher sanity if players talk' },
    de: { name: 'Stimmempfindlichkeit', description: 'Kann bei höherem Geist jagen wenn Spieler sprechen' },
    nl: { name: 'Gevoeligheid voor stemmen', description: 'Kan bij hoger zielkracht jagen bij spreken' },
    fr: { name: 'Sensibilité vocale', description: 'Peut chasser à sanité supérieure si les joueurs parlent' },
    es: { name: 'Sensibilidad vocal', description: 'Puede cazar a mayor cordura si los jugadores hablan' },
    it: { name: 'Sensibilità vocale', description: 'Può cacciare a sanità superiore se i giocatori parlano' },
    pt: { name: 'Sensibilidade vocal', description: 'Pode caçar com sanidade maior se jogadores falarem' },
    sv: { name: 'Röstkänslighet', description: 'Kan jaga vid högre förstånd om spelare talar' },
  },
  hantu_temperature: {
    en: { name: 'Temperature Control', description: 'Moves faster in cold, slower in warm areas' },
    de: { name: 'Temperaturkontrolle', description: 'Schneller in Kälte, langsamer in Wärme' },
    nl: { name: 'Temperatuurcontrole', description: 'Sneller in kou, langzamer in warmte' },
    fr: { name: 'Contrôle de température', description: 'Plus rapide au froid, plus lent au chaud' },
    es: { name: 'Control de temperatura', description: 'Más rápido en frío, más lento en calor' },
    it: { name: 'Controllo della temperatura', description: 'Più veloce al freddo, più lento al caldo' },
    pt: { name: 'Controle de temperatura', description: 'Mais rápido no frio, mais lento no calor' },
    sv: { name: 'Temperatuerkontroll', description: 'Snabbare i kyla, långsammare i värme' },
  },
  goryo_dots: {
    en: { name: 'D.O.T.S. Only Visibility', description: 'Only visible through D.O.T.S. when no players present' },
    de: { name: 'Nur D.O.T.S. Sichtbarkeit', description: 'Nur durch D.O.T.S. sichtbar wenn keine Spieler anwesend' },
    nl: { name: 'Alleen D.O.T.S. zichtbaarheid', description: 'Alleen via D.O.T.S. zichtbaar zonder spelers' },
    fr: { name: 'Visibilité D.O.T.S. uniquement', description: 'Visible uniquement via D.O.T.S. sans joueurs' },
    es: { name: 'Visibilidad solo D.O.T.S.', description: 'Visible solo a través de D.O.T.S. sin jugadores' },
    it: { name: 'Visibilità solo D.O.T.S.', description: 'Visibile solo tramite D.O.T.S. senza giocatori' },
    pt: { name: 'Visibilidade apenas D.O.T.S.', description: 'Visível apenas via D.O.T.S. sem jogadores' },
    sv: { name: 'Endast D.O.T.S. synlighet', description: 'Synlig endast via D.O.T.S. utan spelare' },
  },
  myling_sounds: {
    en: { name: 'Vocal Activity', description: 'Produces paranormal sounds more frequently' },
    de: { name: 'Stimmaktivität', description: 'Erzeugt paranormale Geräusche häufiger' },
    nl: { name: 'Vocale activiteit', description: 'Produceert paranormale geluiden vaker' },
    fr: { name: 'Activité vocale', description: 'Produit des sons paranormaux plus souvent' },
    es: { name: 'Actividad vocal', description: 'Produce sonidos paranormales más frecuentemente' },
    it: { name: 'Attività vocale', description: 'Produce suoni paranormali più frequentemente' },
    pt: { name: 'Atividade vocal', description: 'Produz sons paranormais mais frequentemente' },
    sv: { name: 'Vokal aktivitet', description: 'Producerar paranormala ljud oftare' },
  },
  onryo_flames: {
    en: { name: 'Fire Attraction', description: 'Must hunt after extinguishing 3 flames' },
    de: { name: 'Feueranziehung', description: 'Muss jagen nach 3 Flammen löschen' },
    nl: { name: 'Vuuraantrekking', description: 'Moet jagen na 3 vlammen doven' },
    fr: { name: 'Attraction du feu', description: 'Doit chasser après avoir éteint 3 flammes' },
    es: { name: 'Atracción del fuego', description: 'Debe cazar después de apagar 3 llamas' },
    it: { name: 'Attrazione del fuoco', description: 'Deve cacciare dopo aver spento 3 fiamme' },
    pt: { name: 'Atração do fogo', description: 'Deve caçar depois de apagar 3 chamas' },
    sv: { name: 'Eldattraktion', description: 'Måste jaga efter att ha släckt 3 lågor' },
  },
  twins_dual: {
    en: { name: 'Dual Hunt', description: 'Either twin may start a hunt independently' },
    de: { name: 'Dualjagd', description: 'Jeder Zwilling kann unabhängig jagen' },
    nl: { name: 'Duaal jacht', description: 'Elke tweeling kan onafhankelijk jagen' },
    fr: { name: 'Chasse double', description: 'Chaque jumeau peut chasser indépendamment' },
    es: { name: 'Caza dual', description: 'Cada gemelo puede cazar independientemente' },
    it: { name: 'Caccia doppia', description: 'Ogni gemello può cacciare indipendentemente' },
    pt: { name: 'Caça dupla', description: 'Cada gêmeo pode caçar independentemente' },
    sv: { name: 'Dubbeljakt', description: 'Varje tvilling kan jaga självständigt' },
  },
  raiju_electrical: {
    en: { name: 'Electrical Sensitivity', description: 'Moves faster near active electronics' },
    de: { name: 'Elektrische Empfindlichkeit', description: 'Schneller in der Nähe von aktiver Elektronik' },
    nl: { name: 'Elektrische gevoeligheid', description: 'Sneller dichtbij actieve elektronika' },
    fr: { name: 'Sensibilité électrique', description: 'Plus rapide près de l\'électronique active' },
    es: { name: 'Sensibilidad eléctrica', description: 'Más rápido cerca de electrónica activa' },
    it: { name: 'Sensibilità elettrica', description: 'Più veloce vicino all\'elettronica attiva' },
    pt: { name: 'Sensibilidade elétrica', description: 'Mais rápido perto de eletrônica ativa' },
    sv: { name: 'Elektrisk känslighet', description: 'Snabbare nära aktiv elektronik' },
  },
  obake_shapeshift: {
    en: { name: 'Shapeshifting', description: 'Can briefly shapeshift during hunts' },
    de: { name: 'Gestaltveränderung', description: 'Kann während Jagden kurz Form ändern' },
    nl: { name: 'Gedaanteverwisseling', description: 'Kan kort van vorm veranderen tijdens jachten' },
    fr: { name: 'Métamorphose', description: 'Peut brièvement changer de forme pendant les chasses' },
    es: { name: 'Metamorfosis', description: 'Puede cambiar de forma brevemente durante caza' },
    it: { name: 'Metamorfosi', description: 'Può cambiare forma brevemente durante le cacce' },
    pt: { name: 'Metamorfose', description: 'Pode mudar de forma brevemente durante caçadas' },
    sv: { name: 'Gestaltförändring', description: 'Kan kort byta form under jakter' },
  },
  mimic_mimicry: {
    en: { name: 'Mimicry', description: 'Can mimic abilities of other ghosts' },
    de: { name: 'Mimikry', description: 'Kann Fähigkeiten anderer Geister nachahmen' },
    nl: { name: 'Mimicry', description: 'Kan vaardigheden van andere geesten nabootsen' },
    fr: { name: 'Mimétisme', description: 'Peut imiter les capacités des autres fantômes' },
    es: { name: 'Mimetismo', description: 'Puede imitar habilidades de otros fantasmas' },
    it: { name: 'Mimetismo', description: 'Può imitare le abilità di altri fantasmi' },
    pt: { name: 'Mimetismo', description: 'Pode imitar habilidades de outros fantasmas' },
    sv: { name: 'Mimikri', description: 'Kan härma andra spökes förmågor' },
  },
  moroi_curse: {
    en: { name: 'Curse', description: 'Can curse players via Spirit Box' },
    de: { name: 'Fluch', description: 'Kann Spieler über Spirit Box verfluchen' },
    nl: { name: 'Vloek', description: 'Kan spelers vervloeken via Spirit Box' },
    fr: { name: 'Malédiction', description: 'Peut maudire les joueurs via Spirit Box' },
    es: { name: 'Maldición', description: 'Puede maldecir jugadores via Spirit Box' },
    it: { name: 'Maledizione', description: 'Può maledire i giocatori tramite Spirit Box' },
    pt: { name: 'Maldição', description: 'Pode amaldiçoar jogadores via Spirit Box' },
    sv: { name: 'Förbannelse', description: 'Kan förbannas spelare via Spirit Box' },
  },
  deogen_tracking: {
    en: { name: 'Aggression', description: 'Always knows where player is during hunt' },
    de: { name: 'Aggression', description: 'Kennt immer den Spielerstandort während Jagd' },
    nl: { name: 'Agressie', description: 'Kent altijd spelerslocatie tijdens jacht' },
    fr: { name: 'Agression', description: 'Connaît toujours la position du joueur pendant la chasse' },
    es: { name: 'Agresión', description: 'Siempre conoce la ubicación del jugador durante la caza' },
    it: { name: 'Aggressione', description: 'Conosce sempre la posizione del giocatore durante la caccia' },
    pt: { name: 'Agressão', description: 'Sempre conhece a localização do jogador durante caçada' },
    sv: { name: 'Aggression', description: 'Vet alltid spelarens plats under jakt' },
  },
  thaye_aging: {
    en: { name: 'Aging Process', description: 'Gets faster and more active over time' },
    de: { name: 'Alterungsprozess', description: 'Wird schneller und aktiver mit der Zeit' },
    nl: { name: 'Verouderingsproces', description: 'Wordt sneller en actiever met de tijd' },
    fr: { name: 'Processus de vieillissement', description: 'Devient plus rapide et actif avec le temps' },
    es: { name: 'Proceso de envejecimiento', description: 'Se vuelve más rápido y activo con el tiempo' },
    it: { name: 'Processo di invecchiamento', description: 'Diventa più veloce e attivo nel tempo' },
    pt: { name: 'Processo de envelhecimento', description: 'Fica mais rápido e ativo com o tempo' },
    sv: { name: 'Åldrandeprocess', description: 'Blir snabbare och mer aktivt över tid' },
  },
};

// Ghost Strengths
export const ghostStrengths: Record<string, Record<SupportedLanguage, string>> = {
  spirit_very_active: {
    en: 'Very active - frequently interacts with environment',
    de: 'Sehr aktiv - interagiert häufig mit der Umgebung',
    nl: 'Zeer actief - interageert vaak met de omgeving',
    fr: 'Très actif - interagit fréquemment avec l\'environnement',
    es: 'Muy activo - interactúa frecuentemente con el entorno',
    it: 'Molto attivo - interagisce frequentemente con l\'ambiente',
    pt: 'Muito ativo - interage frequentemente com o ambiente',
    sv: 'Mycket aktiv - interagerar ofta med miljön',
  },
  wraith_walls: {
    en: 'Can pass through walls - ignores physical barriers',
    de: 'Kann durch Wände gehen - ignoriert physische Barrieren',
    nl: 'Kan door muren gaan - negeert fysieke barrières',
    fr: 'Peut passer à travers les murs - ignore les barrières physiques',
    es: 'Puede pasar a través de paredes - ignora barreras físicas',
    it: 'Può passare attraverso i muri - ignora le barriere fisiche',
    pt: 'Pode passar através de paredes - ignora barreiras físicas',
    sv: 'Kan passera genom väggar - ignorerar fysiska barriärer',
  },
  wraith_no_footprints: {
    en: 'No footprints in salt - salt will not reveal it',
    de: 'Keine Fußabdrücke im Salz - Salz offenbart es nicht',
    nl: 'Geen voetafdrukken in zout - zout onthult het niet',
    fr: 'Pas d\'empreintes dans le sel - le sel ne le révèle pas',
    es: 'Sin huellas en la sal - la sal no lo revela',
    it: 'Nessuna impronta nel sale - il sale non lo rivela',
    pt: 'Sem pegadas no sal - o sal não o revela',
    sv: 'Inga fotavtryck i saltet - saltet avslöjar det inte',
  },
  phantom_visible: {
    en: 'More visible during hunts - easier to see and photograph',
    de: 'Sichtbarer während Jagden - leichter zu sehen und zu fotografieren',
    nl: 'Meer zichtbaar tijdens jachten - makkelijker te zien en te fotograferen',
    fr: 'Plus visible pendant les chasses - plus facile à voir et photographier',
    es: 'Más visible durante caza - más fácil de ver y fotografiar',
    it: 'Più visibile durante le cacce - più facile da vedere e fotografare',
    pt: 'Mais visível durante caçadas - mais fácil de ver e fotografar',
    sv: 'Mer synlig under jakter - lättare att se och fotografera',
  },
};

// Ghost Weaknesses
export const ghostWeaknesses: Record<string, Record<SupportedLanguage, string>> = {
  spirit_no_weakness: {
    en: 'No significant weakness - use standard procedures',
    de: 'Keine signifikante Schwäche - verwende Standard-Verfahren',
    nl: 'Geen significante zwakte - gebruik standaardprocedures',
    fr: 'Aucune faiblesse significative - utilisez les procédures standard',
    es: 'Sin debilidad significativa - usa procedimientos estándar',
    it: 'Nessuna debolezza significativa - usa procedure standard',
    pt: 'Nenhuma fraqueza significativa - use procedimentos padrão',
    sv: 'Ingen betydande svaghet - använd standardprocedurer',
  },
  wraith_fears_salt: {
    en: 'Fears salt - place salt near ghost location',
    de: 'Fürchtet Salz - platziere Salz in der Nähe des Geisterortes',
    nl: 'Vreest zout - plaats zout in de buurt van geestlocatie',
    fr: 'Craint le sel - placez le sel près du lieu du fantôme',
    es: 'Teme la sal - coloca sal cerca de la ubicación del fantasma',
    it: 'Teme il sale - posiziona il sale vicino al luogo del fantasma',
    pt: 'Teme sal - coloque sal perto da localização do fantasma',
    sv: 'Fruktar salt - placera salt nära spökplaceringen',
  },
};

/**
 * Helper functions
 */
export const getGhostAbility = (ghostId: string, abilityId: string, language: SupportedLanguage) => {
  const key = `${ghostId}_${abilityId}`;
  return ghostAbilities[key]?.[language] ?? ghostAbilities[key]?.en ?? { name: '', description: '' };
};

export const getGhostStrength = (ghostId: string, strengthId: string, language: SupportedLanguage): string => {
  const key = `${ghostId}_${strengthId}`;
  return ghostStrengths[key]?.[language] ?? ghostStrengths[key]?.en ?? '';
};

export const getGhostWeakness = (ghostId: string, weaknessId: string, language: SupportedLanguage): string => {
  const key = `${ghostId}_${weaknessId}`;
  return ghostWeaknesses[key]?.[language] ?? ghostWeaknesses[key]?.en ?? '';
};
