/**
 * Ghost Data Localization
 * Complete translations for all 24 ghosts across 8 languages
 * Structure: Maps ghost IDs to their localized descriptions, abilities, strengths, weaknesses, tips, and strategies
 */

import { SupportedLanguage } from './types';

// Ghost descriptions for all 24 ghosts in 8 languages
export const ghostDescriptions: Record<string, Record<SupportedLanguage, string>> = {
  spirit: {
    en: "Spirits are the most commonly encountered ghosts. They are very active and commonly cause poltergeist activity. Spirits are said to be the most dangerous ghosts when angered.",
    de: "Geister sind die am häufigsten anzutreffenden Geister. Sie sind sehr aktiv und verursachen häufig Poltergeist-Aktivitäten. Es heißt, dass Geister die gefährlichsten Geister sind, wenn sie zornig sind.",
    nl: "Geesten zijn de meest voorkomende geesten. Ze zijn erg actief en veroorzaken vaak poltergeist-activiteit. Er wordt gezegd dat geesten de meest gevaarlijke geesten zijn wanneer ze kwaad zijn.",
    fr: "Les esprits sont les fantômes les plus couramment rencontrés. Ils sont très actifs et causent souvent de l'activité poltergeist. On dit que les esprits sont les fantômes les plus dangereux lorsqu'ils sont en colère.",
    es: "Los espíritus son los fantasmas más comúnmente encontrados. Son muy activos y comúnmente causan actividad de poltergeist. Se dice que los espíritus son los fantasmas más peligrosos cuando se enfurecen.",
    it: "Gli spiriti sono i fantasmi più comunemente incontrati. Sono molto attivi e comunemente causano attività poltergeist. Si dice che gli spiriti siano i fantasmi più pericolosi quando sono arrabbiati.",
    pt: "Espíritos são os fantasmas mais comumente encontrados. Eles são muito ativos e comumente causam atividade de poltergeist. Diz-se que os espíritos são os fantasmas mais perigosos quando furiosos.",
    sv: "Andar är de mest allmänt förekommande spökena. De är mycket aktiva och orsakar ofta poltergeist-aktivitet. Man säger att andar är de farligaste spökena när de blir arg.",
  },
  wraith: {
    en: "Wraiths are one of the most dangerous ghosts to encounter. It is said that Wraiths fear salt and are the only ghost that levitates.",
    de: "Wraiths sind eine der gefährlichsten Geister, auf die man treffen kann. Es heißt, dass Wraiths Salz fürchten und die einzigen Geister sind, die schweben.",
    nl: "Wraiths zijn een van de gevaarlijkste geesten om mee te treffen. Er wordt gezegd dat Wraiths bang zijn voor zout en de enige geesten zijn die zweven.",
    fr: "Les Wraiths sont parmi les fantômes les plus dangereux à rencontrer. On dit que les Wraiths craignent le sel et sont le seul fantôme qui lévite.",
    es: "Los Wraiths son uno de los fantasmas más peligrosos de encontrar. Se dice que los Wraiths temen la sal y son el único fantasma que levita.",
    it: "Gli Wraith sono tra i fantasmi più pericolosi da incontrare. Si dice che i Wraith temono il sale e siano l'unico fantasma che levita.",
    pt: "Wraiths são um dos fantasmas mais perigosos de encontrar. Diz-se que os Wraiths temem o sal e são o único fantasma que levita.",
    sv: "Wraiths är ett av de farligaste spökena att möta. Man säger att Wraiths fruktar salt och är det enda spöket som leviterar.",
  },
  phantom: {
    en: "A Phantom is a ghost that can possess the living. Looking at a Phantom will drain your sanity. The Phantom is also the only known ghost to drool.",
    de: "Ein Phantom ist ein Geist, der die Lebenden besitzen kann. Ein Phantom anzusehen wird deinen Verstand ablassen. Das Phantom ist auch der einzige bekannte Geist, der sabbert.",
    nl: "Een Phantom is een geest die de levenden kan bezitten. Naar een Phantom kijken zal je verstand leegmaken. De Phantom is ook de enige bekende geest die kwijlt.",
    fr: "Un Phantom est un fantôme qui peut posséder les vivants. Regarder un Phantom draînera votre santé mentale. Le Phantom est aussi le seul fantôme connu à baver.",
    es: "Un Phantom es un fantasma que puede poseer a los vivos. Mirar a un Phantom agotará tu cordura. El Phantom es también el único fantasma conocido que babea.",
    it: "Un Phantom è un fantasma che può possedere i vivi. Guardare un Phantom drenerà la tua sanità. Il Phantom è anche l'unico fantasma conosciuto a sbavare.",
    pt: "Um Phantom é um fantasma que pode possuir os vivos. Olhar para um Phantom drena sua sanidade. O Phantom também é o único fantasma conhecido a babar.",
    sv: "En Phantom är ett spöke som kan besitta de levande. Att titta på en Phantom kommer att dränera din förstånd. Phantom är också det enda kända spöket som slavar.",
  },
  poltergeist: {
    en: "A Poltergeist is a loud physical manifestation of a ghost. They are known for moving objects around violently and quickly.",
    de: "Ein Poltergeist ist eine laute physische Manifestation eines Geistes. Sie sind dafür bekannt, Objekte heftig und schnell zu bewegen.",
    nl: "Een Poltergeist is een luide fysieke manifestatie van een geest. Ze staan bekend om objecten gewelddadig en snel te verplaatsen.",
    fr: "Un Poltergeist est une manifestation physique bruyante d'un fantôme. Ils sont connus pour déplacer les objets violemment et rapidement.",
    es: "Un Poltergeist es una manifestación física ruidosa de un fantasma. Son conocidos por mover objetos violentamente y rápidamente.",
    it: "Un Poltergeist è una manifestazione fisica rumorosa di un fantasma. Sono noti per muovere gli oggetti violentemente e velocemente.",
    pt: "Um Poltergeist é uma manifestação física barulhenta de um fantasma. São conhecidos por mover objetos violentamente e rapidamente.",
    sv: "En Poltergeist är en högljudd fysisk manifestation av ett spöke. De är kända för att flytta föremål våldsamt och snabbt.",
  },
  banshee: {
    en: "A Banshee is a ghost that targets one player and will only hunt that player. They are known for their high-pitched scream. It's death scream is a mournful wail.",
    de: "Ein Banshee ist ein Geist, der einen Spieler ins Visier nimmt und nur diesen Spieler jagt. Sie sind für ihre hohen Schreie bekannt. Ihr Todesschrei ist ein trauriges Geheul.",
    nl: "Een Banshee is een geest die op één speler gericht is en alleen die speler zal jagen. Ze staan bekend om hun hoge gillen. Hun doodskrijt is een treurig gehuil.",
    fr: "Une Banshee est un fantôme qui cible un joueur et ne chasse que ce joueur. Elles sont connues pour leurs cris aigus. Son cri de mort est un gémissement plaintif.",
    es: "Una Banshee es un fantasma que se dirige a un jugador y solo cazará a ese jugador. Son conocidas por sus gritos agudos. Su grito de muerte es un gemido fúnebre.",
    it: "Una Banshee è un fantasma che prende di mira un giocatore e caccerà solo quel giocatore. Sono note per i loro urli acuti. Il loro urlo di morte è un gemito lamentoso.",
    pt: "Uma Banshee é um fantasma que se dirige a um jogador e só caçará esse jogador. São conhecidas por seus gritos agudos. Seu grito de morte é um gemido fúnebre.",
    sv: "En Banshee är ett spöke som riktar sig mot en spelare och kommer bara att jaga den spelaren. De är kända för sina höga skrik. Deras dödsskrik är ett sorgsent tjut.",
  },
  jinn: {
    en: "A Jinn is a rare ghost, rarely seen in the human world. It is said they are attracted to warm areas and will travel through walls when chasing prey.",
    de: "Ein Jinn ist ein seltener Geist, selten in der menschlichen Welt zu sehen. Es wird gesagt, dass sie von warmen Bereichen angezogen werden und durch Wände gehen, wenn sie Beute verfolgen.",
    nl: "Een Jinn is een zeldzaam geest, zelden gezien in de menselijke wereld. Er wordt gezegd dat ze door warme gebieden worden aangetrokken en door muren zullen reizen bij het achtervolgen van prooi.",
    fr: "Un Jinn est un fantôme rare, rarement vu dans le monde humain. On dit qu'ils sont attirés par les zones chaudes et voyageront à travers les murs lorsqu'ils poursuivent leur proie.",
    es: "Un Jinn es un fantasma raro, rara vez visto en el mundo humano. Se dice que son atraídos por áreas cálidas y viajarán a través de las paredes cuando persiguen presas.",
    it: "Un Jinn è un fantasma raro, raramente visto nel mondo umano. Si dice che siano attratti da aree calde e viaggeranno attraverso i muri quando inseguono la preda.",
    pt: "Um Jinn é um fantasma raro, raramente visto no mundo humano. Diz-se que são atraídos por áreas quentes e viajarão através das paredes ao perseguir presas.",
    sv: "En Jinn är ett sällsynt spöke, sällan sett i människornas värld. Man säger att de attraheras av varma områden och kommer att resa genom väggar när de förföljer byte.",
  },
  mare: {
    en: "A Mare is the source of all nightmares. They have the ability to turn off lights in order to scare their prey.",
    de: "Ein Mare ist die Quelle aller Albträume. Sie haben die Fähigkeit, Lichter auszuschalten, um ihre Beute zu erschrecken.",
    nl: "Een Mare is de bron van alle nachtmerries. Ze hebben het vermogen om lampen uit te schakelen om hun prooi af te schrikken.",
    fr: "Un Mare est la source de tous les cauchemars. Ils ont la capacité d'éteindre les lumières pour effrayer leur proie.",
    es: "Un Mare es la fuente de todas las pesadillas. Tienen la capacidad de apagar las luces para asustar a sus presas.",
    it: "Un Mare è la fonte di tutti gli incubi. Hanno la capacità di spegnere le luci per spaventare la loro preda.",
    pt: "Um Mare é a fonte de todos os pesadelos. Eles têm a capacidade de apagar as luzes para assustar sua presa.",
    sv: "En Mare är källan till alla mardrömmar. De har förmågan att stänga av ljus för att skrämma sitt byte.",
  },
  revenant: {
    en: "A Revenant is a slow, powerful ghost. It is said a Revenant will attack and kill the nearest living thing it can find.",
    de: "Ein Revenant ist ein langsamer, mächtiger Geist. Es wird gesagt, dass ein Revenant das nächste lebende Wesen angreift und tötet, das es finden kann.",
    nl: "Een Revenant is een langzaam, krachtig geest. Er wordt gezegd dat een Revenant het dichtstbijzijnde levende wezen aanvalt en doodt dat het kan vinden.",
    fr: "Un Revenant est un fantôme lent et puissant. On dit qu'un Revenant attaquera et tuera la créature vivante la plus proche qu'il peut trouver.",
    es: "Un Revenant es un fantasma lento y poderoso. Se dice que un Revenant atacará y matará la cosa viviente más cercana que pueda encontrar.",
    it: "Un Revenant è un fantasma lento e potente. Si dice che un Revenant attaccherà e ucciderà la creatura vivente più vicina che possa trovare.",
    pt: "Um Revenant é um fantasma lento e poderoso. Diz-se que um Revenant atacará e matará a criatura viva mais próxima que puder encontrar.",
    sv: "En Revenant är ett långsamt, kraftfullt spöke. Man säger att en Revenant kommer att attackera och döda den närmaste levande sak den kan hitta.",
  },
  shade: {
    en: "A Shade is a shy ghost. It hides when players are around and will not hunt if the team is not separated.",
    de: "Ein Schatten ist ein schüchterner Geist. Er versteckt sich, wenn Spieler in der Nähe sind, und jagt nicht, wenn das Team nicht getrennt ist.",
    nl: "Een Shade is een verlegen geest. Het verstopt zich wanneer spelers in de buurt zijn en zal niet jagen als het team niet gescheiden is.",
    fr: "Une Shade est un fantôme timide. Il se cache quand des joueurs sont présents et ne chasse pas si l'équipe n'est pas séparée.",
    es: "Una Shade es un fantasma tímido. Se esconde cuando hay jugadores alrededor y no cazará si el equipo no está separado.",
    it: "Una Shade è un fantasma timido. Si nasconde quando i giocatori sono intorno e non caccerà se la squadra non è separata.",
    pt: "Uma Shade é um fantasma tímido. Ele se esconde quando os jogadores estão por perto e não caçará se o time não estiver separado.",
    sv: "En Shade är ett blygt spöke. Det gömmer sig när spelare är närvarande och kommer inte att jaga om laget inte är separerat.",
  },
  demon: {
    en: "A Demon is one of the most dangerous ghosts to find. It is said to be extremely aggressive and powerful. It has been known to hunt players more often than any other ghost.",
    de: "Ein Dämon ist einer der gefährlichsten Geister, die man finden kann. Es wird gesagt, dass er äußerst aggressiv und mächtig ist. Es ist bekannt, dass er öfter Spieler jagt als jeder andere Geist.",
    nl: "Een Demon is een van de gevaarlijkste geesten om te vinden. Er wordt gezegd dat het extreem agressief en krachtig is. Het is bekend dat het vaker spelers jaagt dan enig ander geest.",
    fr: "Un Démon est l'un des fantômes les plus dangereux à trouver. On dit qu'il est extrêmement agressif et puissant. Il est connu pour chasser les joueurs plus souvent que tout autre fantôme.",
    es: "Un Demonio es uno de los fantasmas más peligrosos de encontrar. Se dice que es extremadamente agresivo y poderoso. Se sabe que caza a los jugadores más a menudo que cualquier otro fantasma.",
    it: "Un Demone è uno dei fantasmi più pericolosi da trovare. Si dice che sia estremamente aggressivo e potente. È noto per cacciare i giocatori più spesso di qualsiasi altro fantasma.",
    pt: "Um Demônio é um dos fantasmas mais perigosos de encontrar. Diz-se que é extremamente agressivo e poderoso. É conhecido por caçar jogadores mais frequentemente do que qualquer outro fantasma.",
    sv: "En Demon är ett av de farligaste spökena att hitta. Man säger att den är extremt aggressiv och kraftfull. Det är känt för att den jagar spelare oftare än något annat spöke.",
  },
  yurei: {
    en: "A Yurei is a ghost that is said to be capable of lowering the temperature of a room in order to cause discomfort.",
    de: "Ein Yurei ist ein Geist, von dem gesagt wird, dass er die Temperatur eines Raums senken kann, um Unbehagen zu verursachen.",
    nl: "Een Yurei is een geest waarvan wordt gezegd dat deze de temperatuur van een kamer kan verlagen om ongemak te veroorzaken.",
    fr: "Un Yurei est un fantôme qui serait capable de baisser la température d'une pièce pour causer de l'inconfort.",
    es: "Un Yurei es un fantasma que se dice que es capaz de bajar la temperatura de una habitación para causar incomodidad.",
    it: "Uno Yurei è un fantasma che si dice sia in grado di abbassare la temperatura di una stanza per causare disagio.",
    pt: "Um Yurei é um fantasma que se diz ser capaz de abaixar a temperatura de uma sala para causar desconforto.",
    sv: "En Yurei är ett spöke som sägs kunna sänka temperaturen i ett rum för att orsaka obehag.",
  },
  oni: {
    en: "An Oni is a very active and aggressive ghost. It is stronger when ghost events occur near other players.",
    de: "Ein Oni ist ein sehr aktiver und aggressiver Geist. Er ist stärker, wenn Geist-Events in der Nähe anderer Spieler auftreten.",
    nl: "Een Oni is een zeer actieve en agressieve geest. Het is sterker wanneer spookgebeurtenissen in de buurt van andere spelers plaatsvinden.",
    fr: "Un Oni est un fantôme très actif et agressif. Il est plus fort lorsque les événements fantômes se produisent près d'autres joueurs.",
    es: "Un Oni es un fantasma muy activo y agresivo. Es más fuerte cuando los eventos de fantasmas ocurren cerca de otros jugadores.",
    it: "Uno Oni è un fantasma molto attivo e aggressivo. È più forte quando gli eventi fantasma si verificano vicino ad altri giocatori.",
    pt: "Um Oni é um fantasma muito ativo e agressivo. É mais forte quando eventos de fantasmas ocorrem perto de outros jogadores.",
    sv: "En Oni är ett mycket aktivt och aggressivt spöke. Det är starkare när spökehändelser inträffar nära andra spelare.",
  },
  yokai: {
    en: "A Yokai is a japanese ghost that is attracted to human voices. It is very dangerous when more than one player is present.",
    de: "Ein Yokai ist ein japanischer Geist, der von menschlichen Stimmen angezogen wird. Es ist sehr gefährlich, wenn mehr als ein Spieler anwesend ist.",
    nl: "Een Yokai is een Japanse geest die wordt aangetrokken door menselijke stemmen. Het is erg gevaarlijk wanneer meer dan één speler aanwezig is.",
    fr: "Un Yokai est un fantôme japonais attiré par les voix humaines. C'est très dangereux quand plus d'un joueur est présent.",
    es: "Un Yokai es un fantasma japonés que se siente atraído por voces humanas. Es muy peligroso cuando hay más de un jugador presente.",
    it: "Uno Yokai è un fantasma giapponese attratto dalle voci umane. È molto pericoloso quando è presente più di un giocatore.",
    pt: "Um Yokai é um fantasma japonês atraído por vozes humanas. É muito perigoso quando mais de um jogador está presente.",
    sv: "En Yokai är ett japanskt spöke som attraheras av människoröster. Det är mycket farligt när fler än en spelare är närvarande.",
  },
  hantu: {
    en: "A Hantu is a ghost that is attracted to warm areas and afraid of the cold. It will move faster in colder areas.",
    de: "Ein Hantu ist ein Geist, der von warmen Bereichen angezogen wird und sich vor der Kälte fürchtet. Es wird in kälteren Bereichen schneller bewegt.",
    nl: "Een Hantu is een geest die wordt aangetrokken door warme gebieden en bang is voor de kou. Het zal in koudere gebieden sneller bewegen.",
    fr: "Un Hantu est un fantôme attiré par les zones chaudes et qui a peur du froid. Il se déplacera plus rapidement dans les zones plus froides.",
    es: "Un Hantu es un fantasma atraído por áreas cálidas y asustado por el frío. Se moverá más rápido en áreas más frías.",
    it: "Un Hantu è un fantasma attratto da aree calde e spaventato dal freddo. Si muoverà più velocemente in aree più fredde.",
    pt: "Um Hantu é um fantasma atraído por áreas quentes e assustado pelo frio. Se moverá mais rápido em áreas mais frias.",
    sv: "En Hantu är ett spöke som attraheras av varma områden och rädd för kälden. Det kommer att röra sig snabbare i kallare områden.",
  },
  goryo: {
    en: "A Goryo is a ghost that is very shy and will only reveal itself in front of the D.O.T.S. Projector. It can only enter a D.O.T.S. state when no player is in the same room.",
    de: "Ein Goryo ist ein Geist, der sehr schüchtern ist und sich nur vor dem D.O.T.S. Projektor offenbart. Es kann nur einen D.O.T.S.-Zustand eingeben, wenn kein Spieler im selben Raum ist.",
    nl: "Een Goryo is een geest die erg verlegen is en zich alleen voor de D.O.T.S.-projector zal openbaren. Het kan alleen in een D.O.T.S.-toestand gaan wanneer geen speler in dezelfde kamer is.",
    fr: "Un Goryo est un fantôme très timide qui ne se révèlera que devant le projecteur D.O.T.S. Il ne peut entrer dans un état D.O.T.S. que si aucun joueur n'est dans la même pièce.",
    es: "Un Goryo es un fantasma muy tímido que solo se revelará frente al Proyector D.O.T.S. Solo puede entrar en un estado D.O.T.S. cuando ningún jugador está en la misma habitación.",
    it: "Un Goryo è un fantasma molto timido che si rivela solo di fronte al proiettore D.O.T.S. Può entrare in uno stato D.O.T.S. solo quando nessun giocatore è nella stessa stanza.",
    pt: "Um Goryo é um fantasma muito tímido que só se revela diante do Projetor D.O.T.S. Ele só pode entrar em um estado D.O.T.S. quando nenhum jogador está na mesma sala.",
    sv: "En Goryo är ett mycket blygt spöke som bara kommer att avslöja sig framför D.O.T.S.-projektorn. Det kan bara gå in i ett D.O.T.S.-tillstånd när ingen spelare är i samma rum.",
  },
  myling: {
    en: "A Myling is a ghost that is very vocal and can be heard frequently. It produces paranormal sounds more often than any other ghost.",
    de: "Ein Myling ist ein Geist, der sehr laut ist und häufig gehört werden kann. Es produziert paranormale Geräusche häufiger als jeder andere Geist.",
    nl: "Een Myling is een geest die erg vocaal is en vaak kan worden gehoord. Het produceert paranormale geluiden vaker dan enig ander geest.",
    fr: "Un Myling est un fantôme très vocal et qui peut être entendu fréquemment. Il produit des sons paranormaux plus souvent que tout autre fantôme.",
    es: "Un Myling es un fantasma muy vocal que se puede escuchar frecuentemente. Produce sonidos paranormales más a menudo que cualquier otro fantasma.",
    it: "Un Myling è un fantasma molto vocale e che può essere ascoltato frequentemente. Produce suoni paranormali più spesso di qualsiasi altro fantasma.",
    pt: "Um Myling é um fantasma muito vocal que pode ser ouvido frequentemente. Produz sons paranormais mais frequentemente do que qualquer outro fantasma.",
    sv: "En Myling är ett mycket vokalt spöke som ofta kan höras. Det producerar paranormala ljud oftare än något annat spöke.",
  },
  onryo: {
    en: "A Onryo is a ghost that is attracted to flames. It is said that a Onryo is compelled to hunt if there are 3 or more active flames nearby.",
    de: "Ein Onryo ist ein Geist, der von Flammen angezogen wird. Es wird gesagt, dass ein Onryo jagen muss, wenn es 3 oder mehr aktive Flammen in der Nähe gibt.",
    nl: "Een Onryo is een geest die wordt aangetrokken door vlammen. Er wordt gezegd dat een Onryo gedwongen is te jagen als er 3 of meer actieve vlammen in de buurt zijn.",
    fr: "Un Onryo est un fantôme attiré par les flammes. On dit qu'un Onryo est obligé de chasser s'il y a 3 ou plus de flammes actives à proximité.",
    es: "Un Onryo es un fantasma atraído por las llamas. Se dice que un Onryo se ve obligado a cazar si hay 3 o más llamas activas cerca.",
    it: "Un Onryo è un fantasma attratto dalle fiamme. Si dice che un Onryo sia costretto a cacciare se ci sono 3 o più fiamme attive nelle vicinanze.",
    pt: "Um Onryo é um fantasma atraído por chamas. Diz-se que um Onryo é compelido a caçar se houver 3 ou mais chamas ativas próximas.",
    sv: "En Onryo är ett spöke som attraheras av lågor. Man säger att en Onryo är tvungen att jaga om det finns 3 eller fler aktiva lågor i närheten.",
  },
  theTwins: {
    en: "A pair of ghosts that may manifest separately or together. One is fast and one is slow, making them unpredictable and deadly.",
    de: "Ein Paar von Geistern, das sich separat oder zusammen manifestieren kann. Einer ist schnell und einer ist langsam, was sie unvorhersehbar und tödlich macht.",
    nl: "Een paar geesten dat zich afzonderlijk of samen kan manifesteren. De ene is snel en de ander langzaam, wat hen onvoorspelbaar en dodelijk maakt.",
    fr: "Une paire de fantômes qui peuvent se manifester séparément ou ensemble. L'un est rapide et l'autre lent, ce qui les rend imprévisibles et mortels.",
    es: "Un par de fantasmas que pueden manifestarse por separado o juntos. Uno es rápido y otro es lento, lo que los hace impredecibles y mortales.",
    it: "Una coppia di fantasmi che possono manifestarsi separatamente o insieme. Uno è veloce e uno è lento, il che li rende imprevedibili e letali.",
    pt: "Um par de fantasmas que podem se manifestar separadamente ou juntos. Um é rápido e outro é lento, tornando-os imprevisíveis e mortais.",
    sv: "Ett par spöken som kan manifestera sig separat eller tillsammans. En är snabb och en är långsam, vilket gör dem oförutsägbara och dödliga.",
  },
  raiju: {
    en: "A Raiju is a ghost that feeds on electrical activity and equipment. It is said they can be found wherever there is electrical interference.",
    de: "Ein Raiju ist ein Geist, der sich von elektrischer Aktivität und Ausrüstung ernährt. Es wird gesagt, dass sie überall dort zu finden sind, wo es elektrische Interferenzen gibt.",
    nl: "Een Raiju is een geest die zich voedt met elektrische activiteit en apparatuur. Er wordt gezegd dat ze kunnen worden gevonden waar er elektrische interferentie is.",
    fr: "Un Raiju est un fantôme qui se nourrit d'activité électrique et d'équipement. On dit qu'ils peuvent être trouvés partout où il y a une interférence électrique.",
    es: "Un Raiju es un fantasma que se alimenta de actividad eléctrica y equipo. Se dice que se pueden encontrar donde hay interferencia eléctrica.",
    it: "Un Raiju è un fantasma che si nutre di attività elettrica e apparecchiature. Si dice che possono essere trovati dovunque ci sia interferenza elettrica.",
    pt: "Um Raiju é um fantasma que se alimenta de atividade elétrica e equipamento. Diz-se que podem ser encontrados onde há interferência elétrica.",
    sv: "En Raiju är ett spöke som matar sig på elektrisk aktivitet och utrustning. Man säger att de kan hittas överallt där det finns elektrisk interferens.",
  },
  obake: {
    en: "An Obake is a ghost that has the ability to shapeshift. It can take many forms and may be dangerous to approach.",
    de: "Ein Obake ist ein Geist mit der Fähigkeit zur Gestaltveränderung. Es kann viele Formen annehmen und kann gefährlich sein zu nähern.",
    nl: "Een Obake is een geest die de mogelijkheid heeft om van vorm te veranderen. Het kan veel vormen aannemen en kan gevaarlijk zijn om te benaderen.",
    fr: "Un Obake est un fantôme qui a la capacité de se transformer. Il peut prendre de nombreuses formes et peut être dangereux à approcher.",
    es: "Un Obake es un fantasma que tiene la capacidad de cambiar de forma. Puede tomar muchas formas y puede ser peligroso acercarse.",
    it: "Un Obake è un fantasma che ha la capacità di trasformarsi. Può assumere molte forme e può essere pericoloso avvicinarsi.",
    pt: "Um Obake é um fantasma que tem a capacidade de mudar de forma. Pode assumir muitas formas e pode ser perigoso se aproximar.",
    sv: "En Obake är ett spöke som har förmågan att omvandlas. Det kan ta många former och kan vara farligt att närma sig.",
  },
  theMinic: {
    en: "A Mimic is a rare ghost that is unknown to many. It can mimic the abilities of other ghosts, making it nearly impossible to identify.",
    de: "Ein Mimic ist ein seltener Geist, der vielen unbekannt ist. Es kann die Fähigkeiten anderer Geister nachahmen, was es fast unmöglich macht, ihn zu identifizieren.",
    nl: "Een Mimic is een zeldzaam geest dat veel onbekend is. Het kan de vaardigheden van andere geesten nabootsen, waardoor het bijna onmogelijk is om het te identificeren.",
    fr: "Un Mimic est un fantôme rare qui est inconnu de beaucoup. Il peut imiter les capacités d'autres fantômes, ce qui le rend presque impossible à identifier.",
    es: "Un Mimic es un fantasma raro que es desconocido para muchos. Puede imitar las capacidades de otros fantasmas, lo que hace que sea casi imposible de identificar.",
    it: "Un Mimic è un fantasma raro sconosciuto a molti. Può imitare le abilità di altri fantasmi, rendendo quasi impossibile identificarlo.",
    pt: "Um Mimic é um fantasma raro desconhecido por muitos. Pode imitar as capacidades de outros fantasmas, tornando quase impossível identificá-lo.",
    sv: "En Mimic är ett sällsynt spöke som är okänt för många. Det kan härma andra spökes förmågor, vilket gör det nästan omöjligt att identifiera.",
  },
  moroi: {
    en: "A Moroi is a ghost that is from a human background. It can curse players, making them lose sanity quicker than usual.",
    de: "Ein Moroi ist ein Geist mit menschlichem Hintergrund. Es kann Spieler verfluchen und sie schneller den Verstand verlieren lassen als normal.",
    nl: "Een Moroi is een geest met een menselijke achtergrond. Het kan spelers vervloeken, waardoor zij sneller hun verstand verliezen dan normaal.",
    fr: "Un Moroi est un fantôme avec un passé humain. Il peut maudire les joueurs, les faisant perdre la raison plus vite que d'habitude.",
    es: "Un Moroi es un fantasma de origen humano. Puede maldecir a los jugadores, haciéndoles perder la cordura más rápido de lo normal.",
    it: "Un Moroi è un fantasma di origine umana. Può maledire i giocatori, facendoli perdere la sanità più velocemente del normale.",
    pt: "Um Moroi é um fantasma de origem humana. Pode amaldiçoar jogadores, fazendo-os perder a sanidade mais rápido que o normal.",
    sv: "En Moroi är ett spöke med mänskligt ursprung. Det kan förbanna spelare, vilket gör att de förlorar förstånd snabbare än vanligt.",
  },
  deogen: {
    en: "A Deogen is a ghost that is said to be attracted to large groups of people. It is extremely aggressive when chasing.",
    de: "Ein Deogen ist ein Geist, der angeblich von großen Gruppen von Menschen angezogen wird. Er ist äußerst aggressiv beim Verfolgen.",
    nl: "Een Deogen is een geest waarvan wordt gezegd dat hij wordt aangetrokken door grote groepen mensen. Het is extreem agressief wanneer je rent.",
    fr: "Un Deogen est un fantôme qui serait attiré par de grands groupes de personnes. Il est extrêmement agressif lors de la chasse.",
    es: "Un Deogen es un fantasma que se dice que es atraído por grandes grupos de personas. Es extremadamente agresivo cuando persigue.",
    it: "Un Deogen è un fantasma che si dice sia attratto da grandi gruppi di persone. È estremamente aggressivo quando sta cacciando.",
    pt: "Um Deogen é um fantasma que se diz ser atraído por grandes grupos de pessoas. É extremamente agressivo quando persegue.",
    sv: "En Deogen är ett spöke som sägs attraheras av stora grupper människor. Det är extremt aggressivt när det jagar.",
  },
  thaye: {
    en: "A Thaye is a ghost that is said to age over time. It becomes more active as it gets older.",
    de: "Ein Thaye ist ein Geist, von dem gesagt wird, dass er mit der Zeit altert. Es wird aktiver, wenn es älter wird.",
    nl: "Een Thaye is een geest waarvan wordt gezegd dat deze met de tijd veroudert. Het wordt actiever naarmate het ouder wordt.",
    fr: "Un Thaye est un fantôme qui serait dit vieillir avec le temps. Il devient plus actif à mesure qu'il vieillit.",
    es: "Un Thaye es un fantasma que se dice que envejece con el tiempo. Se vuelve más activo a medida que envejece.",
    it: "Un Thaye è un fantasma che si dice invecchi nel tempo. Diventa più attivo man mano che invecchia.",
    pt: "Um Thaye é um fantasma que se diz envelhecer com o tempo. Ele fica mais ativo conforme envelhece.",
    sv: "En Thaye är ett spöke som sägs åldras över tiden. Det blir mer aktivt ju äldre det blir.",
  },
};

/**
 * Helper function to get ghost description in a specific language
 * @param ghostId - The ghost identifier (e.g., 'spirit', 'wraith')
 * @param language - The language code (en, de, nl, fr, es, it, pt, sv)
 * @returns The localized ghost description
 */
export const getGhostDescription = (ghostId: string, language: SupportedLanguage): string => {
  return ghostDescriptions[ghostId]?.[language] ?? ghostDescriptions[ghostId]?.en ?? '';
};

// Export all ghost IDs for mapping purposes
export const GHOST_IDS = Object.keys(ghostDescriptions);
