/**
 * Ghost Abilities, Strengths, Weaknesses, and Tips Localization
 * Complete translations for all 24 ghosts across 8 languages
 * Covers abilities, strengths, weaknesses, identification tips, and counter strategies
 */

import { SupportedLanguage } from './types';

// ============================================================================
// GHOST ABILITIES (Names and Descriptions)
// ============================================================================

export const ghostAbilityNames: Record<string, Record<SupportedLanguage, string>> = {
  'spirit.poltergeist': {
    en: 'Poltergeist-like Activity',
    de: 'Poltergeist-ähnliche Aktivität',
    nl: 'Poltergeist-achtige activiteit',
    fr: 'Activité de type Poltergeist',
    es: 'Actividad tipo Poltergeist',
    it: 'Attività simile a Poltergeist',
    pt: 'Atividade tipo Poltergeist',
    sv: 'Poltergeist-liknande aktivitet',
  },
  'wraith.levitation': {
    en: 'Levitation',
    de: 'Levitation',
    nl: 'Zweven',
    fr: 'Lévitation',
    es: 'Levitación',
    it: 'Levitazione',
    pt: 'Levitação',
    sv: 'Levitation',
  },
  'wraith.teleportation': {
    en: 'Teleportation',
    de: 'Teleportation',
    nl: 'Teleportatie',
    fr: 'Téléportation',
    es: 'Teletransportación',
    it: 'Teletrasporto',
    pt: 'Teletransporte',
    sv: 'Teleportation',
  },
  'phantom.possession': {
    en: 'Possession',
    de: 'Besessenheit',
    nl: 'Bezitting',
    fr: 'Possession',
    es: 'Posesión',
    it: 'Possessione',
    pt: 'Possessão',
    sv: 'Possession',
  },
  'phantom.sanity_drain': {
    en: 'Sanity Drain from Sight',
    de: 'Verstandsverlust durch Anblick',
    nl: 'Verstandsverlies door aanblik',
    fr: 'Drainage de santé mentale par la vue',
    es: 'Pérdida de cordura por la vista',
    it: 'Perdita di sanità dalla vista',
    pt: 'Perda de sanidade pela vista',
    sv: 'Förlusting av förstånd från synen',
  },
  'poltergeist.object_throwing': {
    en: 'Object Throwing',
    de: 'Objektwerfen',
    nl: 'Gooien van objecten',
    fr: 'Lancer d\'objets',
    es: 'Lanzamiento de objetos',
    it: 'Lancio di oggetti',
    pt: 'Lançamento de objetos',
    sv: 'Kastning av föremål',
  },
  'banshee.scream': {
    en: 'Scream',
    de: 'Schrei',
    nl: 'Schreeuw',
    fr: 'Cri',
    es: 'Grito',
    it: 'Urlo',
    pt: 'Grito',
    sv: 'Skrik',
  },
  'banshee.singing': {
    en: 'Singing Ghost Event',
    de: 'Singendes Geist-Event',
    nl: 'Zingend spookgebeurtenis',
    fr: 'Événement de fantôme chanteur',
    es: 'Evento de fantasma cantante',
    it: 'Evento fantasma che canta',
    pt: 'Evento de fantasma cantante',
    sv: 'Sjungande spökehändelse',
  },
  'jinn.sanity_drain': {
    en: 'Sanity Drain Ability',
    de: 'Verstandsabzug-Fähigkeit',
    nl: 'Verstandsverlies-vermogen',
    fr: 'Capacité de drainage de santé',
    es: 'Capacidad de pérdida de cordura',
    it: 'Capacità di perdita di sanità',
    pt: 'Capacidade de perda de sanidade',
    sv: 'Förståndstörnande förmåga',
  },
  'mare.light_control': {
    en: 'Light Control',
    de: 'Lichtkontrolle',
    nl: 'Lichtregeling',
    fr: 'Contrôle de la lumière',
    es: 'Control de luz',
    it: 'Controllo della luce',
    pt: 'Controle de luz',
    sv: 'Ljuskontroll',
  },
  'revenant.movement': {
    en: 'Slow/Fast Movement',
    de: 'Langsame/schnelle Bewegung',
    nl: 'Langzaam/snel beweging',
    fr: 'Mouvement lent/rapide',
    es: 'Movimiento lento/rápido',
    it: 'Movimento lento/veloce',
    pt: 'Movimento lento/rápido',
    sv: 'Långsam/snabb rörelse',
  },
  'shade.shyness': {
    en: 'Shyness',
    de: 'Schüchternheit',
    nl: 'Verlegen gedrag',
    fr: 'Timidité',
    es: 'Timidez',
    it: 'Timidezza',
    pt: 'Timidez',
    sv: 'Blyghet',
  },
  'demon.aggression': {
    en: 'Aggression',
    de: 'Aggressivität',
    nl: 'Agressie',
    fr: 'Agressivité',
    es: 'Agresividad',
    it: 'Aggressività',
    pt: 'Agressividade',
    sv: 'Aggression',
  },
  'yurei.door_slamming': {
    en: 'Door Slamming & Sanity Drain',
    de: 'Türenschlag und Verstandsverlust',
    nl: 'Deurslam en verstandsverlies',
    fr: 'Claquement de porte et drainage de santé',
    es: 'Golpe de puerta y pérdida de cordura',
    it: 'Sbattimento di porta e perdita di sanità',
    pt: 'Batida de porta e perda de sanidade',
    sv: 'Dörr som slår och förlusting av förstånd',
  },
  'yurei.smudge_trap': {
    en: 'Smudge Trap',
    de: 'Räucherfalle',
    nl: 'Wierookval',
    fr: 'Piège de sauge',
    es: 'Trampa de salvia',
    it: 'Trappola di salvia',
    pt: 'Armadilha de sálvia',
    sv: 'Rökarfälla',
  },
  'oni.aggression_near_players': {
    en: 'Aggression Near Players',
    de: 'Aggression in der Nähe von Spielern',
    nl: 'Agressie in de buurt van spelers',
    fr: 'Agressivité près des joueurs',
    es: 'Agresividad cerca de jugadores',
    it: 'Aggressività vicino ai giocatori',
    pt: 'Agressividade perto de jogadores',
    sv: 'Aggression nära spelare',
  },
  'oni.collision_drain': {
    en: 'Event Collision Drain',
    de: 'Ereigniskollisionsabzug',
    nl: 'Gebeurtenisbotsingsafzuiging',
    fr: 'Drainage de collision d\'événement',
    es: 'Drenaje de colisión de evento',
    it: 'Drenaggio di collisione evento',
    pt: 'Drenagem de colisão de evento',
    sv: 'Händelsekollisionsdränering',
  },
  'yokai.voice_sensitivity': {
    en: 'Voice Sensitivity',
    de: 'Stimmempfindlichkeit',
    nl: 'Stemgevoeligheid',
    fr: 'Sensibilité vocale',
    es: 'Sensibilidad de voz',
    it: 'Sensibilità vocale',
    pt: 'Sensibilidade de voz',
    sv: 'Röstöverkänslighet',
  },
  'hantu.temperature_control': {
    en: 'Temperature Control',
    de: 'Temperaturkontrolle',
    nl: 'Temperatuurregeling',
    fr: 'Contrôle de la température',
    es: 'Control de temperatura',
    it: 'Controllo della temperatura',
    pt: 'Controle de temperatura',
    sv: 'Temperaturkontroll',
  },
  'hantu.breath_manifestation': {
    en: 'Breath Manifestation',
    de: 'Atemmanifestierung',
    nl: 'Ademmanifestatie',
    fr: 'Manifestation du souffle',
    es: 'Manifestación de aliento',
    it: 'Manifestazione del respiro',
    pt: 'Manifestação do hálito',
    sv: 'Andningsmanifestning',
  },
  'goryo.dots_visibility': {
    en: 'D.O.T.S. Only Visibility',
    de: 'Nur D.O.T.S. Sichtbarkeit',
    nl: 'Alleen D.O.T.S. zichtbaarheid',
    fr: 'Visibilité uniquement D.O.T.S.',
    es: 'Visibilidad solo D.O.T.S.',
    it: 'Visibilità solo D.O.T.S.',
    pt: 'Visibilidade apenas D.O.T.S.',
    sv: 'Endast D.O.T.S. synlighet',
  },
  'myling.vocal_activity': {
    en: 'Vocal Activity',
    de: 'Vokale Aktivität',
    nl: 'Vocale activiteit',
    fr: 'Activité vocale',
    es: 'Actividad vocal',
    it: 'Attività vocale',
    pt: 'Atividade vocal',
    sv: 'Vokalaktivitet',
  },
  'onryo.fire_attraction': {
    en: 'Fire Attraction',
    de: 'Feueranziehung',
    nl: 'Vuurattractie',
    fr: 'Attraction du feu',
    es: 'Atracción del fuego',
    it: 'Attrazione del fuoco',
    pt: 'Atração do fogo',
    sv: 'Eldattraktio',
  },
  'thetwins.dual_hunt': {
    en: 'Dual Hunt',
    de: 'Duale Jagd',
    nl: 'Dubbele jacht',
    fr: 'Chasse double',
    es: 'Caza dual',
    it: 'Caccia doppia',
    pt: 'Caça dupla',
    sv: 'Dubbel jakt',
  },
  'thetwins.coordinated': {
    en: 'Coordinated Interaction',
    de: 'Koordinierte Interaktion',
    nl: 'Gecoördineerde interactie',
    fr: 'Interaction coordonnée',
    es: 'Interacción coordinada',
    it: 'Interazione coordinata',
    pt: 'Interação coordenada',
    sv: 'Koordinerad interaktion',
  },
  'raiju.electrical_sensitivity': {
    en: 'Electrical Sensitivity',
    de: 'Elektrische Empfindlichkeit',
    nl: 'Elektrische gevoeligheid',
    fr: 'Sensibilité électrique',
    es: 'Sensibilidad eléctrica',
    it: 'Sensibilità elettrica',
    pt: 'Sensibilidade elétrica',
    sv: 'Elektrisk överkänslighet',
  },
  'obake.shapeshifting': {
    en: 'Shapeshifting',
    de: 'Gestaltenwechsel',
    nl: 'Gedaanteverwisseling',
    fr: 'Métamorphose',
    es: 'Cambio de forma',
    it: 'Trasformazione',
    pt: 'Mudança de forma',
    sv: 'Skepnadsväxling',
  },
  'obake.fingerprint_manipulation': {
    en: 'Fingerprint Manipulation',
    de: 'Fingerabdruckmanipulation',
    nl: 'Vingerafdrukmanipulatie',
    fr: 'Manipulation des empreintes digitales',
    es: 'Manipulación de huellas dactilares',
    it: 'Manipolazione delle impronte digitali',
    pt: 'Manipulação de impressão digital',
    sv: 'Fingeravtrycksmanipulation',
  },
  'obake.special_fingerprints': {
    en: 'Special Fingerprints',
    de: 'Spezielle Fingerabdrücke',
    nl: 'Speciale vingerafdrukken',
    fr: 'Empreintes digitales spéciales',
    es: 'Huellas dactilares especiales',
    it: 'Impronte digitali speciali',
    pt: 'Impressões digitais especiais',
    sv: 'Speciella fingeravtryck',
  },
  'themimic.mimicry': {
    en: 'Mimicry',
    de: 'Nachahmung',
    nl: 'Nabootsing',
    fr: 'Mimétisme',
    es: 'Imitación',
    it: 'Imitazione',
    pt: 'Imitação',
    sv: 'Mimikry',
  },
  'themimic.fake_ghost_orbs': {
    en: 'Fake Ghost Orbs',
    de: 'Gefälschte Spökerkugeln',
    nl: 'Nep spookbollen',
    fr: 'Fausses orbes fantômes',
    es: 'Orbes fantasmales falsos',
    it: 'Sfere fantasma false',
    pt: 'Orbes fantasmagóricas falsas',
    sv: 'Falska spöksfärer',
  },
  'moroi.curse': {
    en: 'Curse',
    de: 'Fluch',
    nl: 'Vloek',
    fr: 'Malédiction',
    es: 'Maldición',
    it: 'Maledizione',
    pt: 'Maldição',
    sv: 'Förbannelse',
  },
  'moroi.movement_speed': {
    en: 'Movement Speed',
    de: 'Bewegungsgeschwindigkeit',
    nl: 'Bewegingssnelheid',
    fr: 'Vitesse de mouvement',
    es: 'Velocidad de movimiento',
    it: 'Velocità di movimento',
    pt: 'Velocidade de movimento',
    sv: 'Rörelsehastighet',
  },
  'deogen.perfect_tracking': {
    en: 'Perfect Tracking',
    de: 'Perfekte Verfolgung',
    nl: 'Perfecte tracking',
    fr: 'Suivi parfait',
    es: 'Seguimiento perfecto',
    it: 'Tracciamento perfetto',
    pt: 'Rastreamento perfeito',
    sv: 'Perfekt spårning',
  },
  'deogen.slow_proximity': {
    en: 'Slow When Close',
    de: 'Langsam wenn nah',
    nl: 'Langzaam als dicht',
    fr: 'Lent quand près',
    es: 'Lento cuando está cerca',
    it: 'Lento quando vicino',
    pt: 'Lento quando próximo',
    sv: 'Långsam när nära',
  },
  'thaye.aging': {
    en: 'Aging Process',
    de: 'Alterungsprozess',
    nl: 'Verouderingsproces',
    fr: 'Processus de vieillissement',
    es: 'Proceso de envejecimiento',
    it: 'Processo di invecchiamento',
    pt: 'Processo de envelhecimento',
    sv: 'Åldrandeprocess',
  },
  'thaye.time_based_activity': {
    en: 'Time-based Activity',
    de: 'Zeitbasierte Aktivität',
    nl: 'Op tijd gebaseerde activiteit',
    fr: 'Activité basée sur le temps',
    es: 'Actividad basada en el tiempo',
    it: 'Attività basata sul tempo',
    pt: 'Atividade baseada em tempo',
    sv: 'Tidsbaserad aktivitet',
  },
};

// ============================================================================
// GHOST ABILITY DESCRIPTIONS
// ============================================================================

export const ghostAbilityDescriptions: Record<string, Record<SupportedLanguage, string>> = {
  'spirit.poltergeist': {
    en: 'Throws objects around the area',
    de: 'Wirft Objekte in der Umgebung herum',
    nl: 'Gooit objecten rond in het gebied',
    fr: 'Lance des objets autour de la zone',
    es: 'Lanza objetos alrededor del área',
    it: 'Lancia oggetti intorno all\'area',
    pt: 'Lança objetos ao redor da área',
    sv: 'Kastar föremål runt området',
  },
  'wraith.levitation': {
    en: 'Wraith can levitate and pass through objects',
    de: 'Wraith kann schweben und durch Objekte gehen',
    nl: 'Wraith kan zweven en door objecten gaan',
    fr: 'Wraith peut léviter et passer à travers les objets',
    es: 'Wraith puede levitar y pasar a través de objetos',
    it: 'Wraith può levitare e passare attraverso gli oggetti',
    pt: 'Wraith pode levitar e passar através de objetos',
    sv: 'Wraith kan leviterar och passa genom föremål',
  },
  'wraith.teleportation': {
    en: 'Can teleport to players',
    de: 'Kann sich zu Spielern teleportieren',
    nl: 'Kan teleporteren naar spelers',
    fr: 'Peut se téléporter aux joueurs',
    es: 'Puede teletransportarse a los jugadores',
    it: 'Può teletrasportarsi ai giocatori',
    pt: 'Pode se teletransportar para jogadores',
    sv: 'Kan teleportera till spelare',
  },
  'phantom.possession': {
    en: 'Can temporarily control players',
    de: 'Kann Spieler vorübergehend kontrollieren',
    nl: 'Kan spelers tijdelijk controleren',
    fr: 'Peut contrôler temporairement les joueurs',
    es: 'Puede controlar temporalmente a los jugadores',
    it: 'Può controllare temporaneamente i giocatori',
    pt: 'Pode controlar temporariamente os jogadores',
    sv: 'Kan tillfälligt kontrollera spelare',
  },
  'phantom.sanity_drain': {
    en: 'Looking at the phantom drains sanity',
    de: 'Das Anschauen des Phantoms entzieht Verstand',
    nl: 'Naar het fantoom kijken zet verstand af',
    fr: 'Regarder le fantôme draine la santé mentale',
    es: 'Mirar el fantasma drena la cordura',
    it: 'Guardare il fantasma drena la sanità',
    pt: 'Olhar o fantasma drena a sanidade',
    sv: 'Att titta på fantomen tömmer förstånd',
  },
  'poltergeist.object_throwing': {
    en: 'Throws multiple objects at once at high velocities',
    de: 'Wirft mehrere Objekte gleichzeitig mit hoher Geschwindigkeit',
    nl: 'Gooit meerdere objecten tegelijk met hoge snelheid',
    fr: 'Lance plusieurs objets à la fois à grande vitesse',
    es: 'Lanza múltiples objetos a la vez a altas velocidades',
    it: 'Lancia più oggetti contemporaneamente ad alta velocità',
    pt: 'Lança vários objetos ao mesmo tempo em altas velocidades',
    sv: 'Kastar flera föremål på en gång med höga hastigheter',
  },
  'banshee.scream': {
    en: 'Emits a distinctive wail that only affects target',
    de: 'Gibt ein markantes Geheul ab, das nur das Ziel beeinflusst',
    nl: 'Geeft een karakteristiek gehuil af dat alleen het doel beïnvloedt',
    fr: 'Émet un gémissement distinctif qui n\'affecte que la cible',
    es: 'Emite un gemido distintivo que solo afecta al objetivo',
    it: 'Emette un gemito distintivo che colpisce solo il bersaglio',
    pt: 'Emite um gemido distintivo que afeta apenas o alvo',
    sv: 'Utstöter ett karakteristiskt tjut som bara påverkar målet',
  },
  'banshee.singing': {
    en: 'May perform singing events',
    de: 'Kann Singevents durchführen',
    nl: 'Kan zingevents uitvoeren',
    fr: 'Peut effectuer des événements de chant',
    es: 'Puede realizar eventos de canto',
    it: 'Può eseguire eventi di canto',
    pt: 'Pode realizar eventos de canto',
    sv: 'Kan utföra sjungevents',
  },
  'jinn.sanity_drain': {
    en: 'Drains 25% sanity from nearby player when breaker is on',
    de: 'Zieht 25% Verstand von nahegelegenen Spielern ab, wenn der Schalter an ist',
    nl: 'Zet 25% verstand af van dichtbijzijnde spelers als de onderbreker aan is',
    fr: 'Draine 25% de santé mentale du joueur à proximité lorsque le disjoncteur est actif',
    es: 'Drena 25% de cordura del jugador cercano cuando el interruptor está encendido',
    it: 'Drenare 25% di sanità dal giocatore vicino quando il salvavita è attivo',
    pt: 'Drena 25% de sanidade do jogador próximo quando o disjuntor está ativado',
    sv: 'Tömmer 25% förstånd från närliggande spelare när brytaren är på',
  },
  'mare.light_control': {
    en: 'Turns off lights immediately after they are turned on',
    de: 'Schaltet Lichter sofort aus, nachdem sie eingeschaltet wurden',
    nl: 'Schakelt verlichting onmiddellijk uit nadat deze is ingeschakeld',
    fr: 'Éteint les lumières immédiatement après leur allumage',
    es: 'Apaga las luces inmediatamente después de encendidas',
    it: 'Spegne le luci immediatamente dopo che sono state accese',
    pt: 'Apaga as luzes imediatamente depois de acesas',
    sv: 'Slår av ljus omedelbar efter att de har tänts',
  },
  'revenant.movement': {
    en: 'Slow when not detecting players, very fast when it does',
    de: 'Langsam, wenn Spieler nicht erkannt werden, sehr schnell, wenn ja',
    nl: 'Langzaam als spelers niet worden gedetecteerd, zeer snel als dat wel het geval is',
    fr: 'Lent lorsque ne détectant pas les joueurs, très rapide lorsqu\'il le fait',
    es: 'Lento cuando no detecta jugadores, muy rápido cuando lo hace',
    it: 'Lento quando non rileva i giocatori, molto veloce quando lo fa',
    pt: 'Lento quando não detecta jogadores, muito rápido quando detecta',
    sv: 'Långsam när det inte detekterar spelare, mycket snabb när det gör det',
  },
  'shade.shyness': {
    en: 'Avoids activity when players are nearby',
    de: 'Vermeidet Aktivitäten, wenn Spieler in der Nähe sind',
    nl: 'Vermijdt activiteit als spelers in de buurt zijn',
    fr: 'Évite l\'activité quand les joueurs sont à proximité',
    es: 'Evita la actividad cuando los jugadores están cerca',
    it: 'Evita l\'attività quando i giocatori sono nelle vicinanze',
    pt: 'Evita atividade quando os jogadores estão próximos',
    sv: 'Undviker aktivitet när spelare är närvarande',
  },
  'demon.aggression': {
    en: 'Can initiate hunts at any sanity level',
    de: 'Kann Jagden bei jedem Verstandniveau einleiten',
    nl: 'Kan jachtactiviteiten op elk verstands niveau starten',
    fr: 'Peut initier des chasses à tout niveau de santé mentale',
    es: 'Puede iniciar cacerías en cualquier nivel de cordura',
    it: 'Può iniziare cacce a qualsiasi livello di sanità',
    pt: 'Pode iniciar caças em qualquer nível de sanidade',
    sv: 'Kan initiera jakten vid alla förståndsnivåer',
  },
  'yurei.door_slamming': {
    en: 'Slams doors and drains sanity from nearby players',
    de: 'Schlägt Türen zu und zieht Verstand von nahen Spielern ab',
    nl: 'Slaat deuren dicht en zet verstand af van dichtbijzijnde spelers',
    fr: 'Claque les portes et draine la santé mentale des joueurs à proximité',
    es: 'Cierra de golpe las puertas y drena la cordura de jugadores cercanos',
    it: 'Sbatte le porte e drena la sanità dai giocatori vicini',
    pt: 'Bate portas e drena sanidade de jogadores próximos',
    sv: 'Slår igen dörrar och tömmer förstånd från närliggande spelare',
  },
  'yurei.smudge_trap': {
    en: 'Smudging temporarily traps and slows it',
    de: 'Räuchern fängt es vorübergehend ein und verlangsamt es',
    nl: 'Wierooksteken vangt het tijdelijk in en vertraagt het',
    fr: 'La sauge l\'emprisonne temporairement et le ralentit',
    es: 'El sahumerio lo atrapa temporalmente y lo ralentiza',
    it: 'L\'affumicatura lo intrappola temporaneamente e lo rallenta',
    pt: 'Queimar sálvia o aprisiona temporariamente e o desacelera',
    sv: 'Rökning fångar det tillfälligt och bromsar det',
  },
  'oni.aggression_near_players': {
    en: 'More active when other players are nearby during ghost events',
    de: 'Aktiver, wenn andere Spieler während Geistevents in der Nähe sind',
    nl: 'Actiever als andere spelers in de buurt zijn tijdens spookgebeurtenissen',
    fr: 'Plus actif quand d\'autres joueurs sont à proximité lors d\'événements fantômes',
    es: 'Más activo cuando otros jugadores están cerca durante eventos fantasmales',
    it: 'Più attivo quando altri giocatori sono vicini durante gli eventi fantasma',
    pt: 'Mais ativo quando outros jogadores estão próximos durante eventos fantasmais',
    sv: 'Mer aktiv när andra spelare är närvarande under spökehändelser',
  },
  'oni.collision_drain': {
    en: 'Drains 20% sanity when colliding during ghost events',
    de: 'Zieht 20% Verstand ab beim Zusammenprall während Geistevents',
    nl: 'Zet 20% verstand af bij botsing tijdens spookgebeurtenissen',
    fr: 'Draine 20% de santé mentale lors d\'une collision lors d\'événements fantômes',
    es: 'Drena 20% de cordura al colisionar durante eventos fantasmales',
    it: 'Drenare 20% di sanità durante la collisione durante gli eventi fantasma',
    pt: 'Drena 20% de sanidade ao colidir durante eventos fantasmais',
    sv: 'Tömmer 20% förstånd vid kollision under spökehändelser',
  },
  'yokai.voice_sensitivity': {
    en: 'Can hunt at higher sanity if talking is detected',
    de: 'Kann bei höherem Verstand jagen, wenn Sprechen erkannt wird',
    nl: 'Kan bij hoger verstand jagen als spreken wordt gedetecteerd',
    fr: 'Peut chasser à une santé mentale plus élevée si la parole est détectée',
    es: 'Puede cazar con mayor cordura si se detecta la voz',
    it: 'Può cacciare a una sanità più alta se viene rilevata la voce',
    pt: 'Pode caçar com sanidade mais alta se a fala for detectada',
    sv: 'Kan jaga vid högre förstånd om tal detekteras',
  },
  'hantu.temperature_control': {
    en: 'Moves faster in cold, slower in warm areas',
    de: 'Bewegt sich in der Kälte schneller, in warmen Bereichen langsamer',
    nl: 'Beweegt sneller in kou, langzamer in warme gebieden',
    fr: 'Se déplace plus rapidement dans le froid, plus lentement dans les zones chaudes',
    es: 'Se mueve más rápido en el frío, más lento en áreas cálidas',
    it: 'Si muove più velocemente al freddo, più lentamente in aree calde',
    pt: 'Se move mais rápido no frio, mais lento em áreas quentes',
    sv: 'Rör sig snabbare i kallare områden, långsammare i varma områden',
  },
  'hantu.breath_manifestation': {
    en: 'Produces freezing breath during hunts when power is off',
    de: 'Produziert gefrierende Atemzüge während Jagden, wenn die Stromversorgung aus ist',
    nl: 'Produceert vriespeutig adem tijdens jagten wanneer de stroom uit is',
    fr: 'Produit un souffle glacé lors des chasses quand l\'électricité est coupée',
    es: 'Produce aliento congelador durante las cacerías cuando la energía está apagada',
    it: 'Produce fiato congelante durante le cacce quando l\'alimentazione è spenta',
    pt: 'Produz hálito congelante durante as caças quando a energia está desligada',
    sv: 'Producerar frysande andedräkt under jakten när strömmen är av',
  },
  'goryo.dots_visibility': {
    en: 'Can only be seen through D.O.T.S. Projector when no players in room',
    de: 'Kann nur durch D.O.T.S. Projektor gesehen werden, wenn keine Spieler im Raum sind',
    nl: 'Kan alleen via D.O.T.S. projector worden gezien wanneer geen spelers in de kamer zijn',
    fr: 'Ne peut être vu que par le projecteur D.O.T.S. quand il n\'y a pas de joueurs dans la pièce',
    es: 'Solo se puede ver a través del proyector D.O.T.S. cuando no hay jugadores en la habitación',
    it: 'Può essere visto solo attraverso il proiettore D.O.T.S. quando nessun giocatore è nella stanza',
    pt: 'Pode ser visto apenas através do projetor D.O.T.S. quando não há jogadores na sala',
    sv: 'Kan bara ses genom D.O.T.S. projektor när inga spelare är i rummet',
  },
  'myling.vocal_activity': {
    en: 'Produces paranormal sounds more frequently than other ghosts',
    de: 'Produziert paranormale Geräusche häufiger als andere Geister',
    nl: 'Produceert paranormale geluiden frequenter dan andere geesten',
    fr: 'Produit des sons paranormaux plus fréquemment que les autres fantômes',
    es: 'Produce sonidos paranormales más frecuentemente que otros fantasmas',
    it: 'Produce suoni paranormali più frequentemente di altri fantasmi',
    pt: 'Produz sons paranormais mais frequentemente que outros fantasmas',
    sv: 'Producerar paranormala ljud oftare än andra spöken',
  },
  'onryo.fire_attraction': {
    en: 'Will attempt to hunt after extinguishing 3 flames regardless of sanity',
    de: 'Wird versuchen zu jagen, nachdem 3 Flammen gelöscht wurden, unabhängig vom Verstand',
    nl: 'Zal proberen te jagen nadat 3 vlammen zijn gedoofd, ongeacht verstand',
    fr: 'Tentera de chasser après avoir éteint 3 flammes indépendamment de la santé',
    es: 'Intentará cazar después de extinguir 3 llamas independientemente de la cordura',
    it: 'Tenterà di cacciare dopo aver estinto 3 fiamme indipendentemente dalla sanità',
    pt: 'Tentará caçar após apagar 3 chamas independentemente da sanidade',
    sv: 'Kommer att försöka jaga efter att ha släckt 3 lågor oavsett förstånd',
  },
  'thetwins.dual_hunt': {
    en: 'Either twin may start a hunt, not at the same time',
    de: 'Eines der Zwillinge kann eine Jagd beginnen, nicht gleichzeitig',
    nl: 'Elk van de tweeling kan een jacht beginnen, niet tegelijk',
    fr: 'L\'un ou l\'autre jumeau peut commencer une chasse, pas en même temps',
    es: 'Cualquiera de los gemelos puede iniciar una cacería, no al mismo tiempo',
    it: 'Uno dei due gemelli può iniziare una caccia, non allo stesso tempo',
    pt: 'Qualquer um dos gêmeos pode iniciar uma caça, não simultaneamente',
    sv: 'Antingen tvillingen kan starta en jakt, inte samtidigt',
  },
  'thetwins.coordinated': {
    en: 'Will often interact at same time in different places',
    de: 'Werden oft zur gleichen Zeit an verschiedenen Orten interagieren',
    nl: 'Zullen vaak op hetzelfde moment op verschillende plaatsen interageren',
    fr: 'Vont souvent interagir au même moment dans des lieux différents',
    es: 'A menudo interactuarán al mismo tiempo en diferentes lugares',
    it: 'Spesso interagiranno allo stesso tempo in posti diversi',
    pt: 'Frequentemente interagirão ao mesmo tempo em lugares diferentes',
    sv: 'Interagera ofta samtidigt på olika platser',
  },
  'raiju.electrical_sensitivity': {
    en: 'Moves faster near active electronic equipment',
    de: 'Bewegt sich schneller in der Nähe aktiver elektronischer Ausrüstung',
    nl: 'Beweegt sneller in de buurt van actieve elektronische apparatuur',
    fr: 'Se déplace plus rapidement à proximité d\'équipements électroniques actifs',
    es: 'Se mueve más rápido cerca de equipos electrónicos activos',
    it: 'Si muove più velocemente vicino a apparecchiature elettroniche attive',
    pt: 'Se move mais rápido perto de equipamentos eletrônicos ativos',
    sv: 'Rör sig snabbare nära aktiv elektronisk utrustning',
  },
  'obake.shapeshifting': {
    en: 'Can briefly shapeshift into another model during hunts',
    de: 'Kann sich während Jagden kurzzeitig in ein anderes Modell verwandeln',
    nl: 'Kan zich tijdens jagten kort transformeren in een ander model',
    fr: 'Peut brièvement se transformer en un autre modèle lors des chasses',
    es: 'Puede transformarse brevemente en otro modelo durante las cacerías',
    it: 'Può breve trasformarsi in un altro modello durante le cacce',
    pt: 'Pode se transformar brevemente em outro modelo durante as caças',
    sv: 'Kan kort skifta form till en annan modell under jakten',
  },
  'obake.fingerprint_manipulation': {
    en: 'May not leave fingerprints and can cause them to fade',
    de: 'Kann keine Fingerabdrücke hinterlassen und kann sie verblassen lassen',
    nl: 'Kan geen vingerafdrukken achterlaten en kan ze laten vervagen',
    fr: 'Peut ne pas laisser d\'empreintes digitales et peut les faire s\'estomper',
    es: 'Puede no dejar huellas dactilares y puede hacer que se desvanezcan',
    it: 'Potrebbe non lasciare impronte digitali e può farle svanire',
    pt: 'Pode não deixar impressões digitais e pode fazê-las desaparecer',
    sv: 'Kan inte lämna fingeravtryck och kan få dem att blekna',
  },
  'obake.special_fingerprints': {
    en: 'Occasionally leaves unique special fingerprints',
    de: 'Hinterlässt gelegentlich einzigartige spezielle Fingerabdrücke',
    nl: 'Laat zich af en toe unieke speciale vingerafdrukken achter',
    fr: 'Laisse occasionnellement des empreintes digitales spéciales uniques',
    es: 'Ocasionalmente deja huellas dactilares especiales únicas',
    it: 'Occasionalmente lascia impronte digitali speciali uniche',
    pt: 'Ocasionalmente deixa impressões digitais especiais únicas',
    sv: 'Lämnar ibland unika speciella fingeravtryck',
  },
  'themimic.mimicry': {
    en: 'Can mimic the abilities of other ghosts',
    de: 'Kann die Fähigkeiten anderer Geister nachahmen',
    nl: 'Kan de vaardigheden van andere geesten nabootsen',
    fr: 'Peut imiter les capacités d\'autres fantômes',
    es: 'Puede imitar las capacidades de otros fantasmas',
    it: 'Può imitare le capacità di altri fantasmi',
    pt: 'Pode imitar as capacidades de outros fantasmas',
    sv: 'Kan härma andra spökes förmågor',
  },
  'themimic.fake_ghost_orbs': {
    en: 'Will present fake Ghost Orbs as secondary evidence',
    de: 'Wird gefälschte Spöker-Kugeln als Sekundärbeweis präsentieren',
    nl: 'Presenteert nep-spookbollen als secundair bewijs',
    fr: 'Présentera de fausses orbes fantômes comme preuve secondaire',
    es: 'Presentará orbes fantasmales falsos como evidencia secundaria',
    it: 'Presenterà false sfere fantasma come prova secondaria',
    pt: 'Apresentará orbes fantasmagóricas falsas como evidência secundária',
    sv: 'Presenterar falska spöksfärer som sekundär bevis',
  },
  'moroi.curse': {
    en: 'Can curse players via Spirit Box communication',
    de: 'Kann Spieler durch Geisterbox-Kommunikation verfluchen',
    nl: 'Kan spelers vervloeken via geestbox-communicatie',
    fr: 'Peut maudire les joueurs via la communication de la boîte d\'esprits',
    es: 'Puede maldecir a los jugadores a través de la comunicación de espíritus',
    it: 'Può maledire i giocatori tramite la comunicazione della scatola degli spiriti',
    pt: 'Pode amaldiçoar jogadores por meio de comunicação da caixa de espíritos',
    sv: 'Kan förbannas spelarna via Spirit Box-kommunikation',
  },
  'moroi.movement_speed': {
    en: 'Moves faster at low average sanity',
    de: 'Bewegt sich bei niedrigem durchschnittlichen Verstand schneller',
    nl: 'Beweegt zich sneller bij laag gemiddeld verstand',
    fr: 'Se déplace plus rapidement à une santé mentale moyenne faible',
    es: 'Se mueve más rápido con baja cordura promedio',
    it: 'Si muove più velocemente a bassa sanità media',
    pt: 'Se move mais rápido com sanidade média baixa',
    sv: 'Rör sig snabbare vid lågt genomsnittligt förstånd',
  },
  'deogen.perfect_tracking': {
    en: 'Always knows where player is and hunts relentlessly',
    de: 'Weiß immer, wo sich der Spieler befindet und jagt unerbittlich',
    nl: 'Weet altijd waar de speler is en jaagt onverzoenlijk',
    fr: 'Sait toujours où est le joueur et le chasse impitoyablement',
    es: 'Siempre sabe dónde está el jugador y lo caza sin piedad',
    it: 'Sa sempre dove si trova il giocatore e lo insegue inesorabilmente',
    pt: 'Sempre sabe onde está o jogador e o caça implacavelmente',
    sv: 'Vet alltid var spelaren är och jagar den obarmhärtigt',
  },
  'deogen.slow_proximity': {
    en: 'Moves extremely slowly once near its victim',
    de: 'Bewegt sich äußerst langsam, sobald es sein Opfer erreicht',
    nl: 'Beweegt zich extreem langzaam eenmaal dicht bij het slachtoffer',
    fr: 'Se déplace extrêmement lentement une fois près de sa victime',
    es: 'Se mueve extremadamente lento una vez cerca de su víctima',
    it: 'Si muove estremamente lentamente una volta vicino alla sua vittima',
    pt: 'Se move extremamente lento uma vez perto de sua vítima',
    sv: 'Rör sig extremt långsamt när det väl är nära sitt offer',
  },
  'thaye.aging': {
    en: 'Gets faster and more active as time progresses',
    de: 'Wird schneller und aktiver, je mehr Zeit vergeht',
    nl: 'Wordt sneller en actiever naarmate de tijd verstrijkt',
    fr: 'Devient plus rapide et plus actif au fil du temps',
    es: 'Se vuelve más rápido y más activo a medida que avanza el tiempo',
    it: 'Diventa più veloce e più attivo col passare del tempo',
    pt: 'Fica mais rápido e mais ativo conforme o tempo passa',
    sv: 'Blir snabbare och mer aktiv när tiden går',
  },
  'thaye.time_based_activity': {
    en: 'Activity increases significantly after contract start',
    de: 'Die Aktivität nimmt nach Kontraktbeginn erheblich zu',
    nl: 'Activiteit neemt aanzienlijk toe na contractstart',
    fr: 'L\'activité augmente considérablement après le début du contrat',
    es: 'La actividad aumenta significativamente después del inicio del contrato',
    it: 'L\'attività aumenta significativamente dopo l\'inizio del contratto',
    pt: 'A atividade aumenta significativamente após o início do contrato',
    sv: 'Aktiviteten ökar betydligt efter kontraktstart',
  },
};

/**
 * Helper function to get ghost ability name
 */
export const getGhostAbilityName = (abilityKey: string, language: SupportedLanguage): string => {
  return ghostAbilityNames[abilityKey]?.[language] ?? ghostAbilityNames[abilityKey]?.en ?? '';
};

/**
 * Helper function to get ghost ability description
 */
export const getGhostAbilityDescription = (abilityKey: string, language: SupportedLanguage): string => {
  return ghostAbilityDescriptions[abilityKey]?.[language] ?? ghostAbilityDescriptions[abilityKey]?.en ?? '';
};

/**
 * Combined helper to get ability with name and description
 */
export const getGhostAbility = (abilityKey: string, language: SupportedLanguage) => {
  return {
    name: getGhostAbilityName(abilityKey, language),
    description: getGhostAbilityDescription(abilityKey, language),
  };
};
